services:
  pyidcc-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyidcc_crew_control_app
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      # Persistent storage for server logs
      - pyidcc_nginx_logs:/var/log/nginx

  local-autocomplete-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: pyidcc_local_autocomplete_agent
    ports:
      - "5050:5050"
    restart: always
    volumes:
      # Persistent storage for local agent state & logs
      - pyidcc_agent_data:/app/logs

volumes:
  pyidcc_web_data:
    driver: local
  pyidcc_nginx_logs:
    driver: local
  pyidcc_agent_data:
    driver: local
