/**
 * changeoverService.js
 * ─────────────────────────────────────────────────────────────────
 * Night Changeover engine driven by the official Excel file:
 *   "Night Changeover.xlsx" (C:\Users\nages\OneDrive\Desktop\...)
 *
 * The Excel defines EXACTLY which night duties link to which
 * morning-takeover duties for every currentDay→nextDay combination.
 *
 * Column layout in the Excel (per row):
 *  [0]  Duty No
 *  [1]  Sign ON time        (night)
 *  [2]  Sign ON Location    (night)
 *  [3]  Train No            (night)
 *  [4]  Time From           (night leg)
 *  [5]  Time To             (night leg hand-over)
 *  [6]  Trip time           (night leg)
 *  [7]  Handover Location   (night)
 *  [8]  Break               (between night & morning)
 *  [9]  Night Kms
 *  [12] Morn Kms
 *  [13] Takeover Location   (morning)
 *  [14] Train No            (morning)
 *  [15] Time From           (morning leg)
 *  [16] Time To             (morning leg / sign-off)
 *  [17] Trip time           (morning leg)
 *  [18] Handover/Sign-Off Location (morning)
 *  [19] Sign OFF time
 *  [20] Sign Off Location
 *  [21] Total Kms
 *  [22] Duty Hrs
 *  [23] Driving Hrs
 *  [24] Break
 * ─────────────────────────────────────────────────────────────────
 */

import {
  addDoc,
  collection,
  doc,
  getDocs,
  query,
  serverTimestamp,
  setDoc,
  where,
  writeBatch,
} from "firebase/firestore";
import { db } from "../firebase.js";

// ─── Time helpers ────────────────────────────────────────────────
const toSec = (tStr) => {
  if (!tStr || tStr === "--" || tStr === "-" || tStr === "") return -1;
  const parts = String(tStr).split(":").map(Number);
  if (parts.some(isNaN)) return -1;
  return parts[0] * 3600 + parts[1] * 60 + (parts[2] || 0);
};

const toTimeStr = (sec) => {
  if (sec < 0) return "--";
  const hrs = Math.floor(sec / 3600);
  const mins = Math.floor((sec % 3600) / 60);
  const secs = sec % 60;
  return [hrs, mins, secs].map((v) => String(v).padStart(2, "0")).join(":");
};

const getLegDuration = (dep, arr) => {
  const d = toSec(dep),
    a = toSec(arr);
  if (d < 0 || a < 0) return 0;
  let diff = a - d;
  if (diff < 0) diff += 86400;
  return diff;
};

// ─── Changeover table (parsed from Night Changeover.xlsx) ────────
//
//  Key format:  "CURRENT_TYPE__NEXT_TYPE"
//  Each entry:  duty number (zero-padded 2-digit string) → row data
//
// The object below is the authoritative source of truth.
// It exactly mirrors the Excel file.
//
// Structure per duty entry:
// {
//   signOnTime, signOnLocation,
//   nightTrainNo, nightDepTime, nightArrTime, nightTripTime,
//   nightHandoverLoc, nightBreak, nightKms,
//   mornKms, takeoverLocation, mornTrainNo,
//   mornDepTime, mornArrTime, mornTripTime, mornHandoverLoc,
//   signOffTime, signOffLocation,
//   totalKms, dutyHrs, drivingHrs, breakTime
// }

export const CHANGEOVER_TABLE = {
  // ══════════════════════════════════════════════════════════════
  // WEEKDAY Night  ➔  SATURDAY Morning
  // (Row 2 left section of Excel)
  // ══════════════════════════════════════════════════════════════
  WEEKDAY__SATURDAY: {
    64: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "207",
      nightDepTime: "21:32:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:43:00",
      nightHandoverLoc: "APTS Dn",
      nightBreak: "03:50:00",
      nightKms: 75,
      mornKms: 52,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:05:00",
      mornArrTime: "06:30:00",
      mornTripTime: "02:25:00",
      mornHandoverLoc: "KGWA Dn",
      signOffTime: "06:35:00",
      signOffLocation: "KGWA",
      totalKms: 127,
      dutyHrs: "09:20:00",
      drivingHrs: "05:08:00",
      breakTime: "03:50:00",
    },
    65: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Up",
      nightTrainNo: "213",
      nightDepTime: "21:46:00",
      nightArrTime: "23:55:00",
      nightTripTime: "02:09:00",
      nightHandoverLoc: "NLC Up",
      nightBreak: "03:40:00",
      nightKms: 55,
      mornKms: 65,
      takeoverLocation: "NLC Up",
      mornTrainNo: "207",
      mornDepTime: "03:35:00",
      mornArrTime: "06:40:00",
      mornTripTime: "03:05:00",
      mornHandoverLoc: "PUTH",
      signOffTime: "06:45:00",
      signOffLocation: "PUTH",
      totalKms: 120,
      dutyHrs: "09:15:00",
      drivingHrs: "05:13:00",
      breakTime: "03:40:00",
    },
    66: {
      signOnTime: "21:30:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "203",
      nightDepTime: "21:48:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:22:00",
      nightHandoverLoc: "PUTH Dn",
      nightBreak: "04:05:00",
      nightKms: 58,
      mornKms: 47,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "211",
      mornDepTime: "04:15:00",
      mornArrTime: "06:27:00",
      mornTripTime: "02:12:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 105,
      dutyHrs: "09:00:00",
      drivingHrs: "04:34:00",
      breakTime: "04:05:00",
    },
    67: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "212",
      nightDepTime: "21:48:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:27:00",
      nightHandoverLoc: "APTS Up",
      nightBreak: "03:30:00",
      nightKms: 62,
      mornKms: 51,
      takeoverLocation: "APTS Up",
      mornTrainNo: "209",
      mornDepTime: "03:45:00",
      mornArrTime: "06:15:00",
      mornTripTime: "02:30:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "06:20:00",
      signOffLocation: "KGWA",
      totalKms: 113,
      dutyHrs: "08:50:00",
      drivingHrs: "04:57:00",
      breakTime: "03:30:00",
    },
    68: {
      signOnTime: "21:30:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "220",
      nightDepTime: "21:42:00",
      nightArrTime: "23:50:00",
      nightTripTime: "02:08:00",
      nightHandoverLoc: "PUTH Dn",
      nightBreak: "03:50:00",
      nightKms: 58,
      mornKms: 34,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "208",
      mornDepTime: "03:40:00",
      mornArrTime: "05:42:00",
      mornTripTime: "02:02:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "06:00:00",
      signOffLocation: "PYID",
      totalKms: 92,
      dutyHrs: "08:30:00",
      drivingHrs: "04:10:00",
      breakTime: "03:50:00",
    },
    69: {
      signOnTime: "21:05:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "221",
      nightDepTime: "21:22:00",
      nightArrTime: "23:10:00",
      nightTripTime: "01:48:00",
      nightHandoverLoc: "Bt DHO",
      nightBreak: "07:20:00",
      nightKms: 51,
      mornKms: 0,
      takeoverLocation: "BIET DnBE",
      mornTrainNo: "217",
      mornDepTime: "06:30:00",
      mornArrTime: "07:27:00",
      mornTripTime: "00:57:00",
      mornHandoverLoc: "PYID",
      signOffTime: "07:30:00",
      signOffLocation: "PYID",
      totalKms: 51,
      dutyHrs: "10:25:00",
      drivingHrs: "02:45:00",
      breakTime: "07:20:00",
    },
    70: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "208",
      nightDepTime: "21:32:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:38:00",
      nightHandoverLoc: "B DHO",
      nightBreak: "05:35:00",
      nightKms: 61,
      mornKms: 20,
      takeoverLocation: "PYID Dn",
      mornTrainNo: "208",
      mornDepTime: "05:40:00",
      mornArrTime: "06:55:00",
      mornTripTime: "01:15:00",
      mornHandoverLoc: "PUTH",
      signOffTime: "07:00:00",
      signOffLocation: "PUTH",
      totalKms: 81,
      dutyHrs: "09:45:00",
      drivingHrs: "02:38:00",
      breakTime: "05:35:00",
    },
    71: {
      signOnTime: "21:20:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "210",
      nightDepTime: "21:34:00",
      nightArrTime: "23:55:00",
      nightTripTime: "02:21:00",
      nightHandoverLoc: "NGSA DnPF",
      nightBreak: "03:35:00",
      nightKms: 64,
      mornKms: 59,
      takeoverLocation: "NGSA DnPF",
      mornTrainNo: "202",
      mornDepTime: "03:30:00",
      mornArrTime: "06:18:00",
      mornTripTime: "02:48:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "06:25:00",
      signOffLocation: "KGWA",
      totalKms: 123,
      dutyHrs: "09:05:00",
      drivingHrs: "05:09:00",
      breakTime: "03:35:00",
    },
    72: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Up",
      nightTrainNo: "202",
      nightDepTime: "21:37:00",
      nightArrTime: "00:20:00",
      nightTripTime: "02:43:00",
      nightHandoverLoc: "BEIT UpPF",
      nightBreak: "03:50:00",
      nightKms: 75,
      mornKms: 51,
      takeoverLocation: "BEIT UpPF",
      mornTrainNo: "204",
      mornDepTime: "04:10:00",
      mornArrTime: "06:28:00",
      mornTripTime: "02:18:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "06:35:00",
      signOffLocation: "KGWA",
      totalKms: 126,
      dutyHrs: "09:15:00",
      drivingHrs: "05:00:00",
      breakTime: "03:50:00",
    },
    73: {
      signOnTime: "21:25:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "206",
      nightDepTime: "21:42:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:33:00",
      nightHandoverLoc: "SPGD DnPF",
      nightBreak: "03:25:00",
      nightKms: 66,
      mornKms: 58,
      takeoverLocation: "SPGD DnPF",
      mornTrainNo: "201",
      mornDepTime: "03:40:00",
      mornArrTime: "06:37:00",
      mornTripTime: "02:57:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
      totalKms: 124,
      dutyHrs: "09:15:00",
      drivingHrs: "05:30:00",
      breakTime: "03:25:00",
    },
    74: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "215",
      nightDepTime: "21:44:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:31:00",
      nightHandoverLoc: "JIDL UpPF",
      nightBreak: "03:45:00",
      nightKms: 64,
      mornKms: 55,
      takeoverLocation: "JIDL UpPF",
      mornTrainNo: "205",
      mornDepTime: "04:00:00",
      mornArrTime: "06:41:00",
      mornTripTime: "02:41:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "06:45:00",
      signOffLocation: "KGWA",
      totalKms: 119,
      dutyHrs: "09:15:00",
      drivingHrs: "05:12:00",
      breakTime: "03:45:00",
    },
    75: {
      signOnTime: "21:40:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "217",
      nightDepTime: "21:54:00",
      nightArrTime: "00:05:00",
      nightTripTime: "02:11:00",
      nightHandoverLoc: "BIET DnPF",
      nightBreak: "03:40:00",
      nightKms: 62,
      mornKms: 62,
      takeoverLocation: "BIET DnPF",
      mornTrainNo: "203",
      mornDepTime: "03:45:00",
      mornArrTime: "06:33:00",
      mornTripTime: "02:48:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "06:30:00",
      signOffLocation: "KGWA",
      totalKms: 124,
      dutyHrs: "08:50:00",
      drivingHrs: "04:39:00",
      breakTime: "03:40:00",
    },
    76: {
      signOnTime: "21:40:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "223",
      nightDepTime: "21:54:00",
      nightArrTime: "22:40:00",
      nightTripTime: "00:46:00",
      nightHandoverLoc: "N PKT",
      nightBreak: "06:30:00",
      nightKms: 4,
      mornKms: 14,
      takeoverLocation: "Depo - JHLI Trn Bk",
      mornTrainNo: "206",
      mornDepTime: "05:10:00",
      mornArrTime: "06:47:00",
      mornTripTime: "01:37:00",
      mornHandoverLoc: "PYID",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
      totalKms: 18,
      dutyHrs: "09:10:00",
      drivingHrs: "02:22:00",
      breakTime: "06:30:00",
    },
    77: {
      signOnTime: "21:40:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "204",
      nightDepTime: "21:56:00",
      nightArrTime: "23:30:00",
      nightTripTime: "01:34:00",
      nightHandoverLoc: "B DHO",
      nightBreak: "06:00:00",
      nightKms: 15,
      mornKms: 0,
      takeoverLocation: "213; 214; 215",
      mornTrainNo: "PDC",
      mornDepTime: "05:30:00",
      mornArrTime: "07:00:00",
      mornTripTime: "01:30:00",
      mornHandoverLoc: "DEPOT",
      signOffTime: "07:05:00",
      signOffLocation: "PYID",
      totalKms: 15,
      dutyHrs: "09:25:00",
      drivingHrs: "03:04:00",
      breakTime: "06:00:00",
    },
    78: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "Pro 3",
      takeoverLocation: "--",
      mornTrainNo: "Pro 3",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 0,
      nightKms: 0,
      mornKms: 0,
      dutyHrs: "09:00:00",
      drivingHrs: "00:00:00",
    },
    79: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "CC3",
      takeoverLocation: "--",
      mornTrainNo: "CC3",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 0,
      nightKms: 0,
      mornKms: 0,
      dutyHrs: "09:00:00",
      drivingHrs: "00:00:00",
    },
  },

  // ══════════════════════════════════════════════════════════════
  // REGULAR MONDAY Night  ➔  Regular WEEKDAY Morning
  // ══════════════════════════════════════════════════════════════
  MONDAY__WEEKDAY: {
    64: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "207",
      nightDepTime: "21:32:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:43:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 75,
      mornKms: 52,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:35:00",
      mornArrTime: "06:47:00",
      mornTripTime: "02:12:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
      totalKms: 127,
      dutyHrs: "09:35:00",
      drivingHrs: "04:55:00",
    },
    65: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Up",
      nightTrainNo: "213",
      nightDepTime: "21:46:00",
      nightArrTime: "23:55:00",
      nightTripTime: "02:08:00",
      nightHandoverLoc: "NLC Up",
      nightKms: 55,
      mornKms: 65,
      takeoverLocation: "NLC Up",
      mornTrainNo: "207",
      mornDepTime: "04:20:00",
      mornArrTime: "06:30:00",
      mornTripTime: "02:10:00",
      mornHandoverLoc: "KGWA Dn",
      signOffTime: "06:35:00",
      signOffLocation: "KGWA",
      totalKms: 120,
      dutyHrs: "09:05:00",
      drivingHrs: "04:18:00",
    },
    66: {
      signOnTime: "21:30:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "203",
      nightDepTime: "21:48:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:22:00",
      nightHandoverLoc: "PUTH Dn",
      nightKms: 58,
      mornKms: 47,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "211",
      mornDepTime: "04:40:00",
      mornArrTime: "06:57:00",
      mornTripTime: "02:17:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "07:00:00",
      signOffLocation: "PYID",
      totalKms: 105,
      dutyHrs: "09:30:00",
      drivingHrs: "04:39:00",
    },
    67: {
      signOnTime: "21:30:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "212",
      nightDepTime: "21:48:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:27:00",
      nightHandoverLoc: "APTS Up",
      nightKms: 62,
      mornKms: 51,
      takeoverLocation: "APTS Up",
      mornTrainNo: "209",
      mornDepTime: "04:30:00",
      mornArrTime: "06:37:00",
      mornTripTime: "02:07:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
      totalKms: 113,
      dutyHrs: "09:10:00",
      drivingHrs: "04:34:00",
    },
    68: {
      signOnTime: "21:30:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "220",
      nightDepTime: "21:42:00",
      nightArrTime: "23:50:00",
      nightTripTime: "02:08:00",
      nightHandoverLoc: "PUTH Up",
      nightKms: 58,
      mornKms: 34,
      takeoverLocation: "PUTH Up",
      mornTrainNo: "208",
      mornDepTime: "04:15:00",
      mornArrTime: "06:27:00",
      mornTripTime: "02:12:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 92,
      dutyHrs: "09:00:00",
      drivingHrs: "04:20:00",
    },
    69: {
      signOnTime: "21:05:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "221",
      nightDepTime: "21:22:00",
      nightArrTime: "23:10:00",
      nightTripTime: "01:48:00",
      nightHandoverLoc: "BIET DnBE",
      nightKms: 51,
      mornKms: 20,
      takeoverLocation: "BIET DnBE",
      mornTrainNo: "217",
      mornDepTime: "06:30:00",
      mornArrTime: "07:27:00",
      mornTripTime: "00:57:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "07:30:00",
      signOffLocation: "PYID",
      totalKms: 71,
      dutyHrs: "10:25:00",
      drivingHrs: "02:45:00",
    },
    70: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "208",
      nightDepTime: "21:32:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:38:00",
      nightHandoverLoc: "B DHO",
      nightKms: 61,
      mornKms: 20,
      takeoverLocation: "Depot/CC",
      mornTrainNo: "Ntest",
      mornDepTime: "00:40:00",
      mornArrTime: "06:00:00",
      mornTripTime: "05:20:00",
      mornHandoverLoc: "Depot",
      signOffTime: "06:05:00",
      signOffLocation: "Depot",
      totalKms: 81,
      dutyHrs: "08:50:00",
      drivingHrs: "07:58:00",
    },
    71: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "210",
      nightDepTime: "21:34:00",
      nightArrTime: "23:55:00",
      nightTripTime: "02:21:00",
      nightHandoverLoc: "NGSA DnPf",
      nightKms: 64,
      mornKms: 59,
      takeoverLocation: "NGSA DnPf",
      mornTrainNo: "202",
      mornDepTime: "04:00:00",
      mornArrTime: "06:48:00",
      mornTripTime: "02:48:00",
      mornHandoverLoc: "PYID Up",
      signOffTime: "06:55:00",
      signOffLocation: "PYID",
      totalKms: 123,
      dutyHrs: "09:35:00",
      drivingHrs: "05:09:00",
    },
    72: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Up",
      nightTrainNo: "202",
      nightDepTime: "21:37:00",
      nightArrTime: "00:20:00",
      nightTripTime: "02:42:00",
      nightHandoverLoc: "BIET UpPf",
      nightKms: 75,
      mornKms: 51,
      takeoverLocation: "BIET UpPf",
      mornTrainNo: "204",
      mornDepTime: "04:45:00",
      mornArrTime: "06:58:00",
      mornTripTime: "02:13:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "07:05:00",
      signOffLocation: "KGWA",
      totalKms: 126,
      dutyHrs: "09:45:00",
      drivingHrs: "04:55:00",
    },
    73: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "206",
      nightDepTime: "21:42:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:33:00",
      nightHandoverLoc: "SPGD DnPf",
      nightKms: 66,
      mornKms: 58,
      takeoverLocation: "SPGD DnPf",
      mornTrainNo: "201",
      mornDepTime: "04:25:00",
      mornArrTime: "06:33:00",
      mornTripTime: "02:08:00",
      mornHandoverLoc: "PYID Up",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
      totalKms: 124,
      dutyHrs: "09:15:00",
      drivingHrs: "04:41:00",
    },
    74: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "215",
      nightDepTime: "21:44:00",
      nightArrTime: "00:15:00",
      nightTripTime: "02:31:00",
      nightHandoverLoc: "JIDL UpPf",
      nightKms: 64,
      mornKms: 55,
      takeoverLocation: "JIDL UpPf",
      mornTrainNo: "205",
      mornDepTime: "04:45:00",
      mornArrTime: "07:13:00",
      mornTripTime: "02:28:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "07:20:00",
      signOffLocation: "KGWA",
      totalKms: 119,
      dutyHrs: "09:50:00",
      drivingHrs: "04:59:00",
    },
    75: {
      signOnTime: "21:40:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "217",
      nightDepTime: "21:54:00",
      nightArrTime: "00:05:00",
      nightTripTime: "02:11:00",
      nightHandoverLoc: "BIET DnPf",
      nightKms: 62,
      mornKms: 62,
      takeoverLocation: "BIET DnPf",
      mornTrainNo: "203",
      mornDepTime: "04:15:00",
      mornArrTime: "06:43:00",
      mornTripTime: "02:28:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "06:50:00",
      signOffLocation: "KGWA",
      totalKms: 124,
      dutyHrs: "09:10:00",
      drivingHrs: "04:39:00",
    },
    76: {
      signOnTime: "21:40:00",
      signOnLocation: "PYID Up",
      nightTrainNo: "223",
      nightDepTime: "21:54:00",
      nightArrTime: "22:40:00",
      nightTripTime: "00:45:00",
      nightHandoverLoc: "N PKT",
      nightKms: 4,
      mornKms: 14,
      takeoverLocation: "Depo - JHLI Trn Bk",
      mornTrainNo: "206",
      mornDepTime: "04:15:00",
      mornArrTime: "06:15:00",
      mornTripTime: "02:00:00",
      mornHandoverLoc: "KGWA Dn",
      signOffTime: "06:20:00",
      signOffLocation: "KGWA",
      totalKms: 18,
      dutyHrs: "08:40:00",
      drivingHrs: "02:45:00",
    },
    77: {
      signOnTime: "21:40:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "204",
      nightDepTime: "21:56:00",
      nightArrTime: "23:30:00",
      nightTripTime: "01:34:00",
      nightHandoverLoc: "B DHO",
      nightKms: 15,
      mornKms: 0,
      takeoverLocation: "213; 214; 215",
      mornTrainNo: "PDC",
      mornDepTime: "05:30:00",
      mornArrTime: "07:00:00",
      mornTripTime: "01:30:00",
      mornHandoverLoc: "PYID",
      signOffTime: "07:05:00",
      signOffLocation: "PYID",
      totalKms: 15,
      dutyHrs: "09:25:00",
      drivingHrs: "03:04:00",
    },
    78: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "Pro 3",
      takeoverLocation: "--",
      mornTrainNo: "Pro 3",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 0,
      nightKms: 0,
      mornKms: 0,
      dutyHrs: "09:00:00",
      drivingHrs: "00:00:00",
    },
    79: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "CC3",
      takeoverLocation: "--",
      mornTrainNo: "CC3",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 0,
      nightKms: 0,
      mornKms: 0,
      dutyHrs: "09:00:00",
      drivingHrs: "00:00:00",
    },
  },

  // ══════════════════════════════════════════════════════════════
  // SATURDAY Night  ➔  SUNDAY Morning
  // ══════════════════════════════════════════════════════════════
  SATURDAY__SUNDAY: {
    59: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "208",
      nightDepTime: "21:32:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 74,
      mornKms: 41,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:47:00",
      mornArrTime: "06:47:00",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
    },
    60: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "218",
      nightDepTime: "21:42:00",
      nightArrTime: "23:50:00",
      nightHandoverLoc: "PUTH Up",
      nightKms: 58,
      mornKms: 34,
      takeoverLocation: "PUTH Up",
      mornTrainNo: "208",
      mornDepTime: "04:15:00",
      mornArrTime: "06:27:00",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
    },
    61: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "209",
      nightDepTime: "21:45:00",
      nightArrTime: "23:45:00",
      nightHandoverLoc: "NLC Up",
      nightKms: 54,
      mornKms: 38,
      takeoverLocation: "NLC Up",
      mornTrainNo: "207",
      mornDepTime: "04:20:00",
      mornArrTime: "06:30:00",
      signOffTime: "06:35:00",
      signOffLocation: "KGWA",
    },
    62: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "220",
      nightDepTime: "21:30:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "PUTH Dn",
      nightKms: 69,
      mornKms: 47,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "211",
      mornDepTime: "04:40:00",
      mornArrTime: "06:57:00",
      signOffTime: "07:00:00",
      signOffLocation: "PYID",
    },
    63: {
      signOnTime: "21:35:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "203",
      nightDepTime: "21:50:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "APTS Up",
      nightKms: 62,
      mornKms: 40,
      takeoverLocation: "APTS Up",
      mornTrainNo: "209",
      mornDepTime: "04:30:00",
      mornArrTime: "06:37:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    64: {
      signOnTime: "21:05:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "221",
      nightDepTime: "21:22:00",
      nightArrTime: "23:15:00",
      nightHandoverLoc: "BT Dn B/E",
      nightKms: 51,
      mornKms: 7,
      takeoverLocation: "BIET DnBE",
      mornTrainNo: "217",
      mornDepTime: "06:30:00",
      mornArrTime: "07:27:00",
      signOffTime: "07:30:00",
      signOffLocation: "PYID",
    },
    65: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "210",
      nightDepTime: "21:32:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "B DHO",
      nightKms: 59,
      mornKms: 0,
      takeoverLocation: "Depot/CC",
      mornTrainNo: "Ntest",
      mornDepTime: "00:40:00",
      mornArrTime: "06:00:00",
      signOffTime: "06:05:00",
      signOffLocation: "Depot",
    },
    66: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "211",
      nightDepTime: "21:34:00",
      nightArrTime: "22:30:00",
      nightHandoverLoc: "N PKT",
      nightKms: 15,
      mornKms: 0,
      takeoverLocation: "PDC 213;214;215",
      mornTrainNo: "--",
      mornDepTime: "05:30:00",
      mornArrTime: "07:00:00",
      signOffTime: "07:05:00",
      signOffLocation: "PYID",
    },
    67: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "216",
      nightDepTime: "21:34:00",
      nightArrTime: "23:55:00",
      nightHandoverLoc: "NG Dn PF",
      nightKms: 65,
      mornKms: 59,
      takeoverLocation: "NGSA DnPf",
      mornTrainNo: "202",
      mornDepTime: "04:00:00",
      mornArrTime: "06:48:00",
      signOffTime: "06:55:00",
      signOffLocation: "PYID",
    },
    68: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID",
      nightTrainNo: "217",
      nightDepTime: "21:35:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "BIET Up PF",
      nightKms: 74,
      mornKms: 51,
      takeoverLocation: "BIET UpPf",
      mornTrainNo: "204",
      mornDepTime: "04:45:00",
      mornArrTime: "06:58:00",
      signOffTime: "07:05:00",
      signOffLocation: "KGWA",
    },
    69: {
      signOnTime: "21:25:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "201",
      nightDepTime: "21:40:00",
      nightArrTime: "23:30:00",
      nightHandoverLoc: "B DHO",
      nightKms: 36,
      mornKms: 26,
      takeoverLocation: "Depot",
      mornTrainNo: "206",
      mornDepTime: "04:15:00",
      mornArrTime: "06:15:00",
      signOffTime: "06:20:00",
      signOffLocation: "KGWA",
    },
    70: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "202",
      nightDepTime: "21:42:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "SPGD/Depot",
      nightKms: 68,
      mornKms: 45,
      takeoverLocation: "SPGD DnPf",
      mornTrainNo: "201",
      mornDepTime: "04:25:00",
      mornArrTime: "06:33:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    71: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "206",
      nightDepTime: "21:44:00",
      nightArrTime: "00:20:00",
      nightHandoverLoc: "JIDL Up PF",
      nightKms: 60,
      mornKms: 55,
      takeoverLocation: "JIDL UpPf",
      mornTrainNo: "205",
      mornDepTime: "04:45:00",
      mornArrTime: "07:13:00",
      signOffTime: "07:20:00",
      signOffLocation: "KGWA",
    },
    72: {
      signOnTime: "21:35:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "207",
      nightDepTime: "21:54:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "BIET Dn PF",
      nightKms: 62,
      mornKms: 51,
      takeoverLocation: "BIET DnPf",
      mornTrainNo: "203",
      mornDepTime: "04:15:00",
      mornArrTime: "06:43:00",
      signOffTime: "06:50:00",
      signOffLocation: "KGWA",
    },
  },

  // ══════════════════════════════════════════════════════════════
  // SUNDAY Night  ➔  MONDAY (Regular) Morning
  // ══════════════════════════════════════════════════════════════
  SUNDAY__MONDAY: {
    48: {
      signOnTime: "21:05:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "204",
      nightDepTime: "21:22:00",
      nightArrTime: "23:45:00",
      nightTripTime: "02:23:00",
      nightHandoverLoc: "PUTH Up",
      nightKms: 68,
      pilotKms: 21,
      mornKms: 21,
      takeoverLocation: "PUTH Up",
      mornTrainNo: "203",
      mornDepTime: "06:30:00",
      mornArrTime: "07:38:00",
      mornTripTime: "01:08:00",
      mornHandoverLoc: "PYID Up",
      signOffTime: "07:45:00",
      signOffLocation: "PYID",
      totalKms: 110,
      dutyHrs: "10:40:00",
      drivingHrs: "03:31:00",
      breakTime: "06:45:00",
    },
    49: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "215",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:37:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 75,
      pilotKms: 28,
      mornKms: 41,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "204",
      mornDepTime: "06:15:00",
      mornArrTime: "07:48:00",
      mornTripTime: "01:33:00",
      mornHandoverLoc: "PYID Up",
      signOffTime: "07:55:00",
      signOffLocation: "PYID",
      totalKms: 144,
      dutyHrs: "10:40:00",
      drivingHrs: "04:10:00",
      breakTime: "06:05:00",
    },
    50: {
      signOnTime: "21:30:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "216",
      nightDepTime: "21:44:00",
      nightArrTime: "00:00:00",
      nightTripTime: "02:16:00",
      nightHandoverLoc: "APTS Up",
      nightKms: 61,
      pilotKms: 28,
      mornKms: 40,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "202",
      mornDepTime: "05:45:00",
      mornArrTime: "07:28:00",
      mornTripTime: "01:43:00",
      mornHandoverLoc: "PYID Up",
      signOffTime: "07:35:00",
      signOffLocation: "PYID",
      totalKms: 129,
      dutyHrs: "10:05:00",
      drivingHrs: "03:59:00",
      breakTime: "05:45:00",
    },
    51: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "217",
      nightDepTime: "21:44:00",
      nightArrTime: "23:45:00",
      nightTripTime: "02:00:00",
      nightHandoverLoc: "NLC Up",
      nightKms: 55,
      pilotKms: 19,
      mornKms: 30,
      takeoverLocation: "TGTP Dn",
      mornTrainNo: "205",
      mornDepTime: "06:30:00",
      mornArrTime: "07:43:00",
      mornTripTime: "01:13:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "07:50:00",
      signOffLocation: "KGWA",
      totalKms: 104,
      dutyHrs: "10:20:00",
      drivingHrs: "03:13:00",
      breakTime: "06:45:00",
    },
    52: {
      signOnTime: "21:30:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "213",
      nightDepTime: "21:47:00",
      nightArrTime: "00:00:00",
      nightTripTime: "02:13:00",
      nightHandoverLoc: "PUTH Dn",
      nightKms: 58,
      pilotKms: 13,
      mornKms: 40,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "206",
      mornDepTime: "06:30:00",
      mornArrTime: "07:40:00",
      mornTripTime: "01:10:00",
      mornHandoverLoc: "PUTH Up",
      signOffTime: "07:45:00",
      signOffLocation: "PUTH",
      totalKms: 111,
      dutyHrs: "10:15:00",
      drivingHrs: "03:23:00",
      breakTime: "06:30:00",
    },
    53: {
      signOnTime: "21:05:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "214",
      nightDepTime: "21:23:00",
      nightArrTime: "23:40:00",
      nightTripTime: "02:17:00",
      nightHandoverLoc: "B DHO",
      nightKms: 48,
      pilotKms: 2,
      mornKms: 30,
      takeoverLocation: "Depot",
      mornTrainNo: "219",
      mornDepTime: "06:00:00",
      mornArrTime: "07:15:00",
      mornTripTime: "01:15:00",
      mornHandoverLoc: "Rd3 Stbl",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 80,
      dutyHrs: "09:25:00",
      drivingHrs: "03:32:00",
      breakTime: "06:20:00",
    },
    54: {
      signOnTime: "21:10:00",
      signOnLocation: "PYID",
      nightTrainNo: "212",
      nightDepTime: "21:28:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:42:00",
      nightHandoverLoc: "BEIT Dn",
      nightKms: 75,
      pilotKms: 7,
      mornKms: 20,
      takeoverLocation: "BEIT Dn",
      mornTrainNo: "208",
      mornDepTime: "06:30:00",
      mornArrTime: "07:15:00",
      mornTripTime: "00:45:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "07:20:00",
      signOffLocation: "PYID",
      totalKms: 102,
      dutyHrs: "10:10:00",
      drivingHrs: "03:27:00",
      breakTime: "06:20:00",
    },
    55: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "203",
      nightDepTime: "21:32:00",
      nightArrTime: "23:00:00",
      nightTripTime: "01:28:00",
      nightHandoverLoc: "B DHO",
      nightKms: 35,
      pilotKms: 16,
      mornKms: 30,
      takeoverLocation: "Depot",
      mornTrainNo: "211",
      mornDepTime: "06:10:00",
      mornArrTime: "07:39:00",
      mornTripTime: "01:29:00",
      mornHandoverLoc: "PYID DN",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 81,
      dutyHrs: "09:15:00",
      drivingHrs: "02:57:00",
      breakTime: "07:10:00",
    },
    56: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "208",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:37:00",
      nightHandoverLoc: "B DHO",
      nightKms: 59,
      pilotKms: 0,
      mornKms: 0,
      takeoverLocation: "--",
      mornTrainNo: "--",
      mornDepTime: "--",
      mornArrTime: "--",
      mornTripTime: "--",
      mornHandoverLoc: "--",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 59,
      dutyHrs: "09:15:00",
      drivingHrs: "02:37:00",
      breakTime: "06:20:00",
    },
    57: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "216",
      nightDepTime: "21:35:00",
      nightArrTime: "00:00:00",
      nightTripTime: "02:25:00",
      nightHandoverLoc: "NGSA Dn",
      nightKms: 64,
      pilotKms: 47,
      mornKms: 30,
      takeoverLocation: "NGSA Dn",
      mornTrainNo: "201",
      mornDepTime: "05:45:00",
      mornArrTime: "07:00:00",
      mornTripTime: "01:15:00",
      mornHandoverLoc: "KGWA Up",
      signOffTime: "07:05:00",
      signOffLocation: "KGWA",
      totalKms: 141,
      dutyHrs: "09:45:00",
      drivingHrs: "03:40:00",
      breakTime: "05:45:00",
    },
    58: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID",
      nightTrainNo: "202",
      nightDepTime: "21:36:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:33:00",
      nightHandoverLoc: "BEIT Up",
      nightKms: 74,
      pilotKms: 7,
      mornKms: 20,
      takeoverLocation: "BEIT Up",
      mornTrainNo: "209",
      mornDepTime: "06:40:00",
      mornArrTime: "07:22:00",
      mornTripTime: "00:42:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "07:30:00",
      signOffLocation: "PYID",
      totalKms: 101,
      dutyHrs: "10:10:00",
      drivingHrs: "03:15:00",
      breakTime: "06:30:00",
    },
    59: {
      signOnTime: "21:20:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "205",
      nightDepTime: "21:38:00",
      nightArrTime: "23:25:00",
      nightTripTime: "01:47:00",
      nightHandoverLoc: "B DHO",
      nightKms: 36,
      pilotKms: 16,
      mornKms: 35,
      takeoverLocation: "Depot",
      mornTrainNo: "212",
      mornDepTime: "06:15:00",
      mornArrTime: "07:49:00",
      mornTripTime: "01:34:00",
      mornHandoverLoc: "PYID DN",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 87,
      dutyHrs: "09:10:00",
      drivingHrs: "03:21:00",
      breakTime: "06:50:00",
    },
    60: {
      signOnTime: "21:25:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "201",
      nightDepTime: "21:43:00",
      nightArrTime: "23:20:00",
      nightTripTime: "01:37:00",
      nightHandoverLoc: "BT Dn BE",
      nightKms: 41,
      pilotKms: 0,
      mornKms: 0,
      takeoverLocation: "--",
      mornTrainNo: "--",
      mornDepTime: "--",
      mornArrTime: "--",
      mornTripTime: "--",
      mornHandoverLoc: "--",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 41,
      dutyHrs: "09:05:00",
      drivingHrs: "01:37:00",
      breakTime: "07:28:00",
    },
    61: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "209",
      nightDepTime: "21:43:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:27:00",
      nightHandoverLoc: "SPGD Dn",
      nightKms: 66,
      pilotKms: 0,
      mornKms: 0,
      takeoverLocation: "--",
      mornTrainNo: "--",
      mornDepTime: "--",
      mornArrTime: "--",
      mornTripTime: "--",
      mornHandoverLoc: "--",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
      totalKms: 66,
      dutyHrs: "09:05:00",
      drivingHrs: "02:27:00",
      breakTime: "06:38:00",
    },
    62: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "210",
      nightDepTime: "21:45:00",
      nightArrTime: "00:10:00",
      nightTripTime: "02:25:00",
      nightHandoverLoc: "NGSA Up",
      nightKms: 64,
      pilotKms: 10,
      mornKms: 20,
      takeoverLocation: "NGSA Up",
      mornTrainNo: "210",
      mornDepTime: "06:30:00",
      mornArrTime: "07:29:00",
      mornTripTime: "00:59:00",
      mornHandoverLoc: "PYID Dn",
      signOffTime: "07:35:00",
      signOffLocation: "PYID",
      totalKms: 94,
      dutyHrs: "10:05:00",
      drivingHrs: "03:24:00",
      breakTime: "06:20:00",
    },
  },

  // ══════════════════════════════════════════════════════════════
  // SUNDAY Night  ➔  MONDAY GH Morning
  // ══════════════════════════════════════════════════════════════
  SUNDAY__MONDAY_GH: {
    48: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "215",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 75,
      mornKms: 41,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:47:00",
      mornArrTime: "06:47:00",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
    },
    49: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "206",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 75,
      mornKms: 41,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:47:00",
      mornArrTime: "06:47:00",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
    },
    50: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "210",
      nightDepTime: "21:29:00",
      nightArrTime: "23:50:00",
      nightHandoverLoc: "APTS Up",
      nightKms: 57,
      mornKms: 40,
      takeoverLocation: "APTS Up",
      mornTrainNo: "209",
      mornDepTime: "04:30:00",
      mornArrTime: "06:37:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    51: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "202",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 75,
      mornKms: 41,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:47:00",
      mornArrTime: "06:47:00",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
    },
    52: {
      signOnTime: "21:30:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "210",
      nightDepTime: "21:44:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "APTS Up",
      nightKms: 61,
      mornKms: 40,
      takeoverLocation: "APTS Up",
      mornTrainNo: "209",
      mornDepTime: "04:30:00",
      mornArrTime: "06:37:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    53: {
      signOnTime: "21:35:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "208",
      nightDepTime: "21:49:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "PUTH Dn",
      nightKms: 58,
      mornKms: 47,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "211",
      mornDepTime: "04:40:00",
      mornArrTime: "06:57:00",
      signOffTime: "07:00:00",
      signOffLocation: "PYID",
    },
    54: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "214",
      nightDepTime: "21:44:00",
      nightArrTime: "23:40:00",
      nightHandoverLoc: "NLC Up",
      nightKms: 55,
      mornKms: 38,
      takeoverLocation: "NLC Up",
      mornTrainNo: "207",
      mornDepTime: "04:20:00",
      mornArrTime: "06:30:00",
      signOffTime: "06:35:00",
      signOffLocation: "KGWA",
    },
    55: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "215",
      nightDepTime: "21:40:00",
      nightArrTime: "23:40:00",
      nightHandoverLoc: "PUTH Up",
      nightKms: 58,
      mornKms: 34,
      takeoverLocation: "PUTH Up",
      mornTrainNo: "208",
      mornDepTime: "04:15:00",
      mornArrTime: "06:27:00",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
    },
    56: {
      signOnTime: "21:10:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "201",
      nightDepTime: "21:23:00",
      nightArrTime: "23:45:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 48,
      mornKms: 0,
      takeoverLocation: "213; 214; 215",
      mornTrainNo: "--",
      mornDepTime: "05:30:00",
      mornArrTime: "07:00:00",
      signOffTime: "07:05:00",
      signOffLocation: "PYID",
    },
    57: {
      signOnTime: "21:10:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "211",
      nightDepTime: "21:23:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 59,
      mornKms: 0,
      takeoverLocation: "Depot/CC",
      mornTrainNo: "Ntest",
      mornDepTime: "00:40:00",
      mornArrTime: "06:00:00",
      signOffTime: "06:05:00",
      signOffLocation: "Depot",
    },
    58: {
      signOnTime: "21:15:00",
      signOnLocation: "PYID",
      nightTrainNo: "213",
      nightDepTime: "21:28:00",
      nightArrTime: "23:55:00",
      nightHandoverLoc: "BEIT Dn",
      nightKms: 74,
      mornKms: 51,
      takeoverLocation: "BEIT Dn",
      mornTrainNo: "203",
      mornDepTime: "04:15:00",
      mornArrTime: "06:43:00",
      signOffTime: "06:50:00",
      signOffLocation: "KGWA",
    },
    59: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "203",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 59,
      mornKms: 0,
      takeoverLocation: "CC/Depot",
      mornTrainNo: "N test",
      mornDepTime: "00:40:00",
      mornArrTime: "06:30:00",
      signOffTime: "06:30:00",
      signOffLocation: "Depot",
    },
    60: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "204",
      nightDepTime: "21:35:00",
      nightArrTime: "23:55:00",
      nightHandoverLoc: "NGSA Dn",
      nightKms: 64,
      mornKms: 59,
      takeoverLocation: "NGSA DnPf",
      mornTrainNo: "202",
      mornDepTime: "04:00:00",
      mornArrTime: "06:48:00",
      signOffTime: "06:55:00",
      signOffLocation: "PYID",
    },
    61: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID",
      nightTrainNo: "206",
      nightDepTime: "21:36:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "BEIT Up",
      nightKms: 74,
      mornKms: 51,
      takeoverLocation: "BIET UpPf",
      mornTrainNo: "204",
      mornDepTime: "04:45:00",
      mornArrTime: "06:58:00",
      signOffTime: "07:05:00",
      signOffLocation: "KGWA",
    },
    62: {
      signOnTime: "21:30:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "212",
      nightDepTime: "21:43:00",
      nightArrTime: "00:05:00",
      nightHandoverLoc: "SPGD Dn",
      nightKms: 66,
      mornKms: 45,
      takeoverLocation: "SPGD DnPf",
      mornTrainNo: "201",
      mornDepTime: "04:25:00",
      mornArrTime: "06:33:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
  },

  // ══════════════════════════════════════════════════════════════
  // MONDAY_GH Night  ➔  WEEKDAY Morning
  // ══════════════════════════════════════════════════════════════
  MONDAY_GH__WEEKDAY: {
    51: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "202",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 75,
      mornKms: 41,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:47:00",
      mornArrTime: "06:47:00",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
    },
    52: {
      signOnTime: "21:30:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "210",
      nightDepTime: "21:44:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "APTS Up",
      nightKms: 61,
      mornKms: 40,
      takeoverLocation: "APTS Up",
      mornTrainNo: "209",
      mornDepTime: "04:30:00",
      mornArrTime: "06:37:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    53: {
      signOnTime: "21:35:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "208",
      nightDepTime: "21:49:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "PUTH Dn",
      nightKms: 58,
      mornKms: 47,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "211",
      mornDepTime: "04:40:00",
      mornArrTime: "06:57:00",
      signOffTime: "07:00:00",
      signOffLocation: "PYID",
    },
    54: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "214",
      nightDepTime: "21:44:00",
      nightArrTime: "23:40:00",
      nightHandoverLoc: "NLC Up",
      nightKms: 55,
      mornKms: 38,
      takeoverLocation: "NLC Up",
      mornTrainNo: "207",
      mornDepTime: "04:20:00",
      mornArrTime: "06:30:00",
      signOffTime: "06:35:00",
      signOffLocation: "KGWA",
    },
    55: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "215",
      nightDepTime: "21:40:00",
      nightArrTime: "23:40:00",
      nightHandoverLoc: "PUTH Up",
      nightKms: 58,
      mornKms: 34,
      takeoverLocation: "PUTH Up",
      mornTrainNo: "208",
      mornDepTime: "04:15:00",
      mornArrTime: "06:27:00",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
    },
    56: {
      signOnTime: "21:10:00",
      signOnLocation: "PUTH Dn",
      nightTrainNo: "201",
      nightDepTime: "21:23:00",
      nightArrTime: "23:45:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 48,
      mornKms: 0,
      takeoverLocation: "213; 214; 215",
      mornTrainNo: "--",
      mornDepTime: "05:30:00",
      mornArrTime: "07:00:00",
      signOffTime: "07:05:00",
      signOffLocation: "PYID",
    },
    57: {
      signOnTime: "21:10:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "211",
      nightDepTime: "21:23:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 59,
      mornKms: 0,
      takeoverLocation: "Depot/CC",
      mornTrainNo: "Ntest",
      mornDepTime: "00:40:00",
      mornArrTime: "06:00:00",
      signOffTime: "06:05:00",
      signOffLocation: "Depot",
    },
    58: {
      signOnTime: "21:15:00",
      signOnLocation: "PYID",
      nightTrainNo: "213",
      nightDepTime: "21:28:00",
      nightArrTime: "23:55:00",
      nightHandoverLoc: "BEIT Dn",
      nightKms: 74,
      mornKms: 51,
      takeoverLocation: "BEIT Dn",
      mornTrainNo: "203",
      mornDepTime: "04:15:00",
      mornArrTime: "06:43:00",
      signOffTime: "06:50:00",
      signOffLocation: "KGWA",
    },
    59: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "203",
      nightDepTime: "21:33:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 59,
      mornKms: 0,
      takeoverLocation: "CC/Depot",
      mornTrainNo: "N test",
      mornDepTime: "00:40:00",
      mornArrTime: "06:30:00",
      signOffTime: "06:30:00",
      signOffLocation: "Depot",
    },
    60: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "204",
      nightDepTime: "21:35:00",
      nightArrTime: "23:55:00",
      nightHandoverLoc: "NGSA Dn",
      nightKms: 64,
      mornKms: 59,
      takeoverLocation: "NGSA DnPf",
      mornTrainNo: "202",
      mornDepTime: "04:00:00",
      mornArrTime: "06:48:00",
      signOffTime: "06:55:00",
      signOffLocation: "PYID",
    },
    61: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID",
      nightTrainNo: "206",
      nightDepTime: "21:36:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "BEIT Up",
      nightKms: 74,
      mornKms: 51,
      takeoverLocation: "BIET UpPf",
      mornTrainNo: "204",
      mornDepTime: "04:45:00",
      mornArrTime: "06:58:00",
      signOffTime: "07:05:00",
      signOffLocation: "KGWA",
    },
    62: {
      signOnTime: "21:30:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "212",
      nightDepTime: "21:43:00",
      nightArrTime: "00:05:00",
      nightHandoverLoc: "SPGD Dn",
      nightKms: 66,
      mornKms: 45,
      takeoverLocation: "SPGD DnPf",
      mornTrainNo: "201",
      mornDepTime: "04:25:00",
      mornArrTime: "06:33:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    63: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "205",
      nightDepTime: "21:45:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "JIDL Up",
      nightKms: 64,
      mornKms: 55,
      takeoverLocation: "JIDL UpPf",
      mornTrainNo: "205",
      mornDepTime: "04:45:00",
      mornArrTime: "07:13:00",
      signOffTime: "07:20:00",
      signOffLocation: "KGWA",
    },
    64: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "207",
      nightDepTime: "21:32:00",
      nightArrTime: "23:00:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 25,
      mornKms: 7,
      takeoverLocation: "BIET DnBE",
      mornTrainNo: "217",
      mornDepTime: "06:30:00",
      mornArrTime: "07:27:00",
      signOffTime: "07:30:00",
      signOffLocation: "PYID",
    },
    65: {
      signOnTime: "21:20:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "209",
      nightDepTime: "21:38:00",
      nightArrTime: "23:25:00",
      nightHandoverLoc: "Bt DHO",
      nightKms: 36,
      mornKms: 26,
      takeoverLocation: "Depo - JHLI Trn Bk",
      mornTrainNo: "206",
      mornDepTime: "04:15:00",
      mornArrTime: "06:15:00",
      signOffTime: "06:20:00",
      signOffLocation: "KGWA",
    },
  },

  // ══════════════════════════════════════════════════════════════
  // SATURDAY Night  ➔  WEEKDAY Morning (Saturday→Weekday)
  // ══════════════════════════════════════════════════════════════
  SATURDAY__WEEKDAY: {
    59: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "208",
      nightDepTime: "21:32:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "APTS Dn",
      nightKms: 74,
      mornKms: 41,
      takeoverLocation: "APTS Dn",
      mornTrainNo: "210",
      mornDepTime: "04:47:00",
      mornArrTime: "06:47:00",
      signOffTime: "06:50:00",
      signOffLocation: "PYID",
    },
    60: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "218",
      nightDepTime: "21:42:00",
      nightArrTime: "23:50:00",
      nightHandoverLoc: "PUTH Up",
      nightKms: 58,
      mornKms: 34,
      takeoverLocation: "PUTH Up",
      mornTrainNo: "208",
      mornDepTime: "04:15:00",
      mornArrTime: "06:27:00",
      signOffTime: "06:30:00",
      signOffLocation: "PYID",
    },
    61: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID",
      nightTrainNo: "209",
      nightDepTime: "21:45:00",
      nightArrTime: "23:45:00",
      nightHandoverLoc: "NLC Up",
      nightKms: 54,
      mornKms: 38,
      takeoverLocation: "NLC Up",
      mornTrainNo: "207",
      mornDepTime: "04:20:00",
      mornArrTime: "06:30:00",
      signOffTime: "06:35:00",
      signOffLocation: "KGWA",
    },
    62: {
      signOnTime: "21:15:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "220",
      nightDepTime: "21:30:00",
      nightArrTime: "00:10:00",
      nightHandoverLoc: "PUTH Dn",
      nightKms: 69,
      mornKms: 47,
      takeoverLocation: "PUTH Dn",
      mornTrainNo: "211",
      mornDepTime: "04:40:00",
      mornArrTime: "06:57:00",
      signOffTime: "07:00:00",
      signOffLocation: "PYID",
    },
    63: {
      signOnTime: "21:35:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "203",
      nightDepTime: "21:50:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "APTS Up",
      nightKms: 62,
      mornKms: 40,
      takeoverLocation: "APTS Up",
      mornTrainNo: "209",
      mornDepTime: "04:30:00",
      mornArrTime: "06:37:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    64: {
      signOnTime: "21:05:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "221",
      nightDepTime: "21:22:00",
      nightArrTime: "23:15:00",
      nightHandoverLoc: "BT Dn B/E",
      nightKms: 51,
      mornKms: 7,
      takeoverLocation: "BIET DnBE",
      mornTrainNo: "217",
      mornDepTime: "06:30:00",
      mornArrTime: "07:27:00",
      signOffTime: "07:30:00",
      signOffLocation: "PYID",
    },
    65: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "210",
      nightDepTime: "21:32:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "B DHO",
      nightKms: 59,
      mornKms: 0,
      takeoverLocation: "Depot/CC",
      mornTrainNo: "Ntest",
      mornDepTime: "00:40:00",
      mornArrTime: "06:00:00",
      signOffTime: "06:05:00",
      signOffLocation: "Depot",
    },
    66: {
      signOnTime: "21:15:00",
      signOnLocation: "KGWA Up",
      nightTrainNo: "211",
      nightDepTime: "21:34:00",
      nightArrTime: "22:30:00",
      nightHandoverLoc: "N PKT",
      nightKms: 15,
      mornKms: 0,
      takeoverLocation: "PDC 213;214;215",
      mornTrainNo: "--",
      mornDepTime: "05:30:00",
      mornArrTime: "07:00:00",
      signOffTime: "07:05:00",
      signOffLocation: "PYID",
    },
    67: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "216",
      nightDepTime: "21:34:00",
      nightArrTime: "23:55:00",
      nightHandoverLoc: "NG Dn PF",
      nightKms: 65,
      mornKms: 59,
      takeoverLocation: "NGSA DnPf",
      mornTrainNo: "202",
      mornDepTime: "04:00:00",
      mornArrTime: "06:48:00",
      signOffTime: "06:55:00",
      signOffLocation: "PYID",
    },
    68: {
      signOnTime: "21:20:00",
      signOnLocation: "PYID",
      nightTrainNo: "217",
      nightDepTime: "21:35:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "BIET Up PF",
      nightKms: 74,
      mornKms: 51,
      takeoverLocation: "BIET UpPf",
      mornTrainNo: "204",
      mornDepTime: "04:45:00",
      mornArrTime: "06:58:00",
      signOffTime: "07:05:00",
      signOffLocation: "KGWA",
    },
    69: {
      signOnTime: "21:25:00",
      signOnLocation: "PUTH Up",
      nightTrainNo: "201",
      nightDepTime: "21:40:00",
      nightArrTime: "23:30:00",
      nightHandoverLoc: "B DHO",
      nightKms: 36,
      mornKms: 26,
      takeoverLocation: "Depot",
      mornTrainNo: "206",
      mornDepTime: "04:15:00",
      mornArrTime: "06:15:00",
      signOffTime: "06:20:00",
      signOffLocation: "KGWA",
    },
    70: {
      signOnTime: "21:25:00",
      signOnLocation: "KGWA Dn",
      nightTrainNo: "202",
      nightDepTime: "21:42:00",
      nightArrTime: "00:00:00",
      nightHandoverLoc: "SPGD/Depot",
      nightKms: 68,
      mornKms: 45,
      takeoverLocation: "SPGD DnPf",
      mornTrainNo: "201",
      mornDepTime: "04:25:00",
      mornArrTime: "06:33:00",
      signOffTime: "06:40:00",
      signOffLocation: "PYID",
    },
    71: {
      signOnTime: "21:30:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "206",
      nightDepTime: "21:44:00",
      nightArrTime: "00:20:00",
      nightHandoverLoc: "JIDL Up PF",
      nightKms: 60,
      mornKms: 55,
      takeoverLocation: "JIDL UpPf",
      mornTrainNo: "205",
      mornDepTime: "04:45:00",
      mornArrTime: "07:13:00",
      signOffTime: "07:20:00",
      signOffLocation: "KGWA",
    },
    72: {
      signOnTime: "21:35:00",
      signOnLocation: "PYID Dn",
      nightTrainNo: "207",
      nightDepTime: "21:54:00",
      nightArrTime: "00:15:00",
      nightHandoverLoc: "BIET Dn PF",
      nightKms: 62,
      mornKms: 51,
      takeoverLocation: "BIET DnPf",
      mornTrainNo: "203",
      mornDepTime: "04:15:00",
      mornArrTime: "06:43:00",
      signOffTime: "06:50:00",
      signOffLocation: "KGWA",
    },
  },
};

// ─── Helper: get the changeover table key ────────────────────────
function getTableKey(currentDay, nextDay) {
  // Normalise nextDay alias: MONDAY maps to MONDAY
  const cd = currentDay.toUpperCase();
  const nd = nextDay.toUpperCase();
  return `${cd}__${nd}`;
}

// ─── Helper: check if trip is pure PDC (excluding Depo/No PDC) ───
export function isPdcTrip(str) {
  if (!str) return false;
  const s = String(str).toLowerCase();
  if (
    s.includes("no pdc") ||
    s.includes("nopdc") ||
    s.includes("no-pdc") ||
    s.includes("no_pdc")
  ) {
    return false; // Depo / No PDC -> RUNNING TRIP (KM Calculated!)
  }
  return s.includes("pdc");
}

// ─── Build an ACTIVE_RUN duty document from a changeover row ─────
function buildActiveRunDuty(coRow, existingCurrentDuty) {
  // Night side maps to leg1 + leg2 (existing link roster fields)
  // Morning side maps to leg3 (takeover train) fields

  const nightDrivingSec = getLegDuration(
    coRow.nightDepTime,
    coRow.nightArrTime,
  );
  const mornDrivingSec = getLegDuration(coRow.mornDepTime, coRow.mornArrTime);
  const totalDrivingSec = nightDrivingSec + mornDrivingSec;

  const signOnSec = toSec(coRow.signOnTime);
  const signOffSec = toSec(coRow.signOffTime);
  let workSec = signOffSec - signOnSec;
  if (workSec < 0) workSec += 86400;

  // Carry over existing formatting if present
  const baseFormatting = existingCurrentDuty?.formatting || {};

  const isMornPdc =
    isPdcTrip(coRow.mornTrainNo) || isPdcTrip(coRow.takeoverLocation);
  const mornKmsVal = isMornPdc ? 0 : coRow.mornKms || 0;
  const totalKmsVal = coRow.totalKms || (coRow.nightKms || 0) + mornKmsVal;

  return {
    // Identity
    scheduleType: "ACTIVE_RUN",
    dutyId: coRow.dutyNo,

    // Sign On (from changeover night side)
    signOnTime: coRow.signOnTime,
    signOnLocation: coRow.signOnLocation,
    trainId: String(coRow.nightTrainNo),

    // Leg 1 = night drive leg
    leg1TimeFrom: coRow.nightDepTime,
    leg1TimeTo: coRow.nightArrTime,
    leg1TripTime: coRow.nightTripTime || toTimeStr(nightDrivingSec),
    leg1HandoverLoc: coRow.nightHandoverLoc,

    // Leg 2 = break / idle (night handover → morning takeover)
    leg2DepLoc: coRow.nightHandoverLoc,
    leg2TrainNo: "--",
    leg2DepTime: coRow.nightArrTime,
    leg2ArrTime: coRow.mornDepTime,
    leg2TimeTo: coRow.nightBreak || "--",
    leg2ArrLoc: coRow.takeoverLocation,

    // Leg 3 = morning takeover train
    leg3DepLoc: coRow.takeoverLocation,
    leg3TrainNo: String(coRow.mornTrainNo),
    leg3DepTime: coRow.mornDepTime,
    leg3ArrTime: coRow.mornArrTime,
    leg3TimeTo: coRow.mornTripTime || toTimeStr(mornDrivingSec),
    leg3ArrLoc: coRow.mornHandoverLoc || coRow.signOffLocation,

    // Leg 4 (not applicable for standard changeover)
    leg4FinalDepLoc: "--",
    leg4TrainNo: "--",
    leg4FinalDepTime: "--",
    leg4FinalArrTime: "--",
    leg4TimeTo: "--",
    leg4FinalArrLoc: "--",

    // Sign Off
    signOffTime: coRow.signOffTime,
    signOffLocation: coRow.signOffLocation,

    // KMs (Dynamically computed from WTT & Changeover table)
    nightKms: coRow.nightKms || 0,
    mornKms: mornKmsVal,
    totalKms: totalKmsVal,
    leg1Km: coRow.nightKms || 0,
    leg2Km: 0,
    leg3Km: mornKmsVal,
    leg4Km: 0,
    totalKm: totalKmsVal,

    // Calculated hours
    remarks:
      totalDrivingSec > 0
        ? toTimeStr(totalDrivingSec)
        : coRow.drivingHrs || "--",
    totalHours: workSec > 0 ? toTimeStr(workSec) : coRow.dutyHrs || "--",

    // Preserve existing cell formatting from the base link roster
    formatting: baseFormatting,

    lastModified: new Date().toISOString(),
  };
}

// ─── Auto-Enrichment Helper for Changeover Metrics ─────────────
export function enrichChangeoverTable(tableObj) {
  if (!tableObj || typeof tableObj !== "object") return tableObj;
  Object.keys(tableObj).forEach((key) => {
    const subObj = tableObj[key];
    if (subObj && typeof subObj === "object") {
      if (subObj.signOnTime || subObj.nightDepTime) {
        enrichRow(subObj);
      } else {
        Object.keys(subObj).forEach((dNo) => {
          if (subObj[dNo] && typeof subObj[dNo] === "object") {
            enrichRow(subObj[dNo]);
          }
        });
      }
    }
  });
  return tableObj;
}

function enrichRow(row) {
  const nK = Number(row.nightKms) || 0;
  const mK = Number(row.mornKms) || 0;
  if (!row.totalKms || row.totalKms === "--" || Number(row.totalKms) === 0) {
    row.totalKms = nK + mK;
  }

  const nDep = toSec(row.nightDepTime);
  const nArr = toSec(row.nightArrTime);
  let nTrip = -1;
  if (nDep >= 0 && nArr >= 0) {
    nTrip = nArr < nDep ? nArr + 86400 - nDep : nArr - nDep;
  }
  if (!row.nightTripTime || row.nightTripTime === "--") {
    row.nightTripTime = toTimeStr(nTrip);
  }

  const mDep = toSec(row.mornDepTime);
  const mArr = toSec(row.mornArrTime);
  let mTrip = -1;
  if (mDep >= 0 && mArr >= 0) {
    mTrip = mArr < mDep ? mArr + 86400 - mDep : mArr - mDep;
  }
  if (!row.mornTripTime || row.mornTripTime === "--") {
    row.mornTripTime = toTimeStr(mTrip);
  }

  if (!row.nightBreak || row.nightBreak === "--") {
    if (nArr >= 0 && mDep >= 0) {
      let rBreak = mDep < nArr ? mDep + 86400 - nArr : mDep - nArr;
      row.nightBreak = toTimeStr(rBreak);
    }
  }

  const sOn = toSec(row.signOnTime);
  const sOff = toSec(row.signOffTime);
  let dHrs = -1;
  if (sOn >= 0 && sOff >= 0) {
    dHrs = sOff < sOn ? sOff + 86400 - sOn : sOff - sOn;
  }
  if (!row.dutyHrs || row.dutyHrs === "--") {
    row.dutyHrs = toTimeStr(dHrs);
  }

  let drSecs = -1;
  if (nTrip >= 0 || mTrip >= 0) {
    drSecs = (nTrip > 0 ? nTrip : 0) + (mTrip > 0 ? mTrip : 0);
  }
  if (!row.drivingHrs || row.drivingHrs === "--") {
    row.drivingHrs = toTimeStr(drSecs);
  }

  if (!row.breakTime || row.breakTime === "--") {
    if (dHrs >= 0 && drSecs >= 0) {
      row.breakTime = toTimeStr(Math.max(0, dHrs - drSecs));
    }
  }
}

// Auto-run enrichment on default CHANGEOVER_TABLE
enrichChangeoverTable(CHANGEOVER_TABLE);

export function getChangeoverMappings() {
  return enrichChangeoverTable(CHANGEOVER_TABLE);
}

// ─── Main export ─────────────────────────────────────────────────
export const triggerChangeover = async (currentDay, nextDay) => {
  const tableKey = getTableKey(currentDay, nextDay);
  const coTable = CHANGEOVER_TABLE[tableKey];

  if (!coTable) {
    throw new Error(
      `No changeover table found for: ${currentDay} → ${nextDay}.\n` +
        `Supported combinations: ${Object.keys(CHANGEOVER_TABLE)
          .map((k) => k.replace("__", "→"))
          .join(", ")}`,
    );
  }

  // ── 1. Fetch the current-day base roster (to carry over formatting / day duties) ──
  const currentSnap = await getDocs(
    query(
      collection(db, "crew_final_links"),
      where("scheduleType", "==", currentDay),
    ),
  );
  const currentDutyMap = {};
  currentSnap.docs.forEach((d) => {
    const data = d.data();
    currentDutyMap[String(data.dutyId).padStart(2, "0")] = {
      id: d.id,
      ...data,
    };
  });

  // ── 2. Delete all existing ACTIVE_RUN duties ──
  const activeSnap = await getDocs(
    query(
      collection(db, "crew_final_links"),
      where("scheduleType", "==", "ACTIVE_RUN"),
    ),
  );
  const deleteBatch = writeBatch(db);
  activeSnap.docs.forEach((d) => deleteBatch.delete(d.ref));
  await deleteBatch.commit();

  // ── 3. Build new ACTIVE_RUN duties ──
  const writeBatchInst = writeBatch(db);

  // (a) Night changeover duties — built from the Excel table
  const changeoverDutyIds = new Set();
  Object.entries(coTable).forEach(([dutyNo, coRow]) => {
    changeoverDutyIds.add(dutyNo);
    const existingCurrentDuty = currentDutyMap[dutyNo];
    const finalDuty = buildActiveRunDuty(
      { ...coRow, dutyNo },
      existingCurrentDuty,
    );
    const docId = `link_active_run_duty_${dutyNo}`;
    writeBatchInst.set(doc(db, "crew_final_links", docId), finalDuty);
  });

  // (b) Day duties from current-day roster (not in the changeover table) — kept as-is
  Object.entries(currentDutyMap).forEach(([dutyNo, dutyData]) => {
    if (changeoverDutyIds.has(dutyNo)) return; // already handled above
    const finalDuty = {
      ...dutyData,
      scheduleType: "ACTIVE_RUN",
      lastModified: new Date().toISOString(),
    };
    const docId = `link_active_run_duty_${dutyNo}`;
    writeBatchInst.set(doc(db, "crew_final_links", docId), finalDuty);
  });

  await writeBatchInst.commit();

  // ── 4. Update system settings ──
  await setDoc(
    doc(db, "system_settings", "active_roster_config"),
    {
      activeDayType: "ACTIVE_RUN",
      currentDay: currentDay,
      nextDay: nextDay,
      lastChangeover: serverTimestamp(),
    },
    { merge: true },
  );

  // ── 5. Write audit log ──
  await addDoc(collection(db, "auditLogs"), {
    action: "SCHEDULE_CHANGEOVER",
    from: `${currentDay} Night`,
    to: `${nextDay} Morning`,
    tableKey: tableKey,
    nightDuties: Object.keys(coTable).length,
    timestamp: serverTimestamp(),
    performedBy: "System Admin",
  });

  return `ACTIVE_RUN (${currentDay} ➔ ${nextDay}) — ${Object.keys(coTable).length} night duties merged`;
};

export const revertToNormalRoster = async () => {
  // Delete all ACTIVE_RUN duties
  const activeSnap = await getDocs(
    query(
      collection(db, "crew_final_links"),
      where("scheduleType", "==", "ACTIVE_RUN"),
    ),
  );
  const deleteBatch = writeBatch(db);
  activeSnap.docs.forEach((d) => deleteBatch.delete(d.ref));
  await deleteBatch.commit();

  // Reset active_roster_config
  await setDoc(
    doc(db, "system_settings", "active_roster_config"),
    {
      activeDayType: "WEEKDAY",
      currentDay: "WEEKDAY",
      nextDay: "SATURDAY",
      lastRevert: serverTimestamp(),
    },
    { merge: true },
  );

  await addDoc(collection(db, "auditLogs"), {
    action: "REVERT_CHANGEOVER",
    timestamp: serverTimestamp(),
    performedBy: "System Admin",
  });

  return "Roster successfully reverted back to standard timetable schedule.";
};
