export const DAY_TYPES = {
  WEEKDAY: 'WEEKDAY',
  MONDAY: 'MONDAY',
  MONDAY_GH: 'MONDAY_GH',
  SATURDAY: 'SATURDAY',
  GH: 'GAZETTED_HOLIDAY',
  SUNDAY: 'SUNDAY'
};

// Based on your operational flow
export const ROSTER_TRANSITION_RULES = {
  [DAY_TYPES.SUNDAY]: DAY_TYPES.MONDAY,
  [DAY_TYPES.MONDAY]: DAY_TYPES.WEEKDAY,
  [DAY_TYPES.WEEKDAY]: DAY_TYPES.SATURDAY,
  [DAY_TYPES.SATURDAY]: DAY_TYPES.SUNDAY,
  [DAY_TYPES.MONDAY_GH]: DAY_TYPES.WEEKDAY,
  [DAY_TYPES.GH]: DAY_TYPES.WEEKDAY
};

export const getNextSchedule = (current) => ROSTER_TRANSITION_RULES[current] || DAY_TYPES.WEEKDAY;
