export const BMRCL_CREW_REGISTRY = [
  { "id": "20009", "name": "GOURIVARAGOUDA.G", "designation": "Station Superintendent", "contact": "8951218783", "email": "scto_gourivaragouda@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20010", "name": "BHARATH N", "designation": "Station Superintendent", "contact": "9986532957", "email": "scto_bharathn@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20011", "name": "ARUN JT", "designation": "Station Superintendent", "contact": "8277895179", "email": "arunjt@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20012", "name": "VINAY KUMAR S", "designation": "Station Superintendent", "contact": "9620643949", "email": "scto_vinaykumars@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20013", "name": "PRAKASH", "designation": "Station Superintendent", "contact": "9845944289", "email": "mkprakash@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20014", "name": "SATISH.A", "designation": "Station Superintendent", "contact": "9964965958", "email": "scto_satisha@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20015", "name": "PRADEEP P", "designation": "Station Superintendent", "contact": "9480825731", "email": "scto_pradeepp@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20016", "name": "VEERASWAMY.G", "designation": "Station Superintendent", "contact": "8660206534", "email": "scto_veeraswamyg@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20018", "name": "ARUNKUMAR D S", "designation": "Station Superintendent", "contact": "9480800083", "email": "scto_arunkumards@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20019", "name": "MUTHURAMAN S", "designation": "Station Superintendent", "contact": "9900406059", "email": "scto_muthuraman@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20020", "name": "RATHNAKAR K", "designation": "Station Superintendent", "contact": "9739890684", "email": "scto_rathnakar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20021", "name": "BALACHANDRAN N", "designation": "Station Superintendent", "contact": "9449908947", "email": "scto_balachandran@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20022", "name": "ANGEL RANI", "designation": "Station Controller / Train Operator", "contact": "", "email": "scto_angelrani@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20057", "name": "SHANTHIRAJ S", "designation": "Station Superintendent", "contact": "9900358337", "email": "scto_shanthirajs@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20188", "name": "BASAVARAJ HIREGOUDAR", "designation": "Station Controller / Train Operator", "contact": "9739610260", "email": "scto_basavaraj@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20200", "name": "MALLIKARJUN NARAYANAKAR", "designation": "Station Controller / Train Operator", "contact": "9845884992", "email": "scto_mallikarjunn@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20809", "name": "RAMESH BABU D", "designation": "Station Controller / Train Operator", "contact": "9900707847", "email": "itsupport@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20811", "name": "AJAT KUMAR SAHU", "designation": "Station Controller / Train Operator", "contact": "9901151804", "email": "scto_ajatkumar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20812", "name": "RAMKUMAR SINGH", "designation": "Station Controller / Train Operator", "contact": "7760043185", "email": "ramkumar162438b@yahoo.com", "competencyExpiry": "" },
  { "id": "20815", "name": "SURINDER KUMAR", "designation": "Station Controller / Train Operator", "contact": "7204865756", "email": "spgd@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20817", "name": "PAVITHRAN K", "designation": "Station Controller / Train Operator", "contact": "8951753433", "email": "pavithrank@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20818", "name": "KAMALA KANNAN V", "designation": "Station Controller / Train Operator", "contact": "8105087228", "email": "dcc_bypt@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20820", "name": "SURAJ KUMAR CHAURASIA", "designation": "Station Controller / Train Operator", "contact": "7022389420", "email": "nlc@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20821", "name": "JOHNSON KUZHIKANDATHIL JOSEPH", "designation": "Station Controller / Train Operator", "contact": "7892119298", "email": "kjjohnson5@gmail.com", "competencyExpiry": "" },
  { "id": "20822", "name": "FARUQUE HOSSAIN", "designation": "Station Controller / Train Operator", "contact": "9611783972", "email": "cbpk@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20823", "name": "BHARAT LAL NIRALA", "designation": "Station Controller / Train Operator", "contact": "8892177250", "email": "bharatlalnirala@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20824", "name": "SANJIB KUMAR RANA", "designation": "Station Controller / Train Operator", "contact": "9739403608", "email": "pyid@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20825", "name": "SUGUMARAN S", "designation": "Station Controller / Train Operator", "contact": "9900306769", "email": "scto_sugumaran@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20826", "name": "RAGHUBIR PRASAD", "designation": "Station Controller / Train Operator", "contact": "8660949986", "email": "scto_raghubir@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20827", "name": "RAGHU GANESAN G", "designation": "Station Controller / Train Operator", "contact": "9742431857", "email": "scto_raghuganesan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20841", "name": "SHREEKANTHA SANGAPPA ALURU", "designation": "Station Controller / Train Operator", "contact": "8431668166", "email": "shree.1061901@gmail.com", "competencyExpiry": "" },
  { "id": "20885", "name": "DIVYA L", "designation": "Station Controller / Train Operator", "contact": "9901318433", "email": "divyalakshmana94@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20887", "name": "BHAVYA M", "designation": "Station Controller / Train Operator", "contact": "8892780827", "email": "bavya00882gmail.com", "competencyExpiry": "" },
  { "id": "20890", "name": "PRAKASHA TN", "designation": "Station Controller / Train Operator", "contact": "7975981465", "email": "tnpgowda@bmrc.co.in", "competencyExpiry": "" },
  { "id": "20896", "name": "RENUKAMMA R", "designation": "Station Controller / Train Operator", "contact": "9980085448", "email": "scto_renuka@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21069", "name": "NAVEENA I P", "designation": "Station Controller / Train Operator", "contact": "9900468353", "email": "naveenip_scto@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21070", "name": "MURALEEDHARA", "designation": "Station Controller / Train Operator", "contact": "8970108603", "email": "muraleedhara@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21071", "name": "RAGHU.K", "designation": "Station Controller / Train Operator", "contact": "8951384944", "email": "raghuk@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21073", "name": "SHILPA R", "designation": "Station Controller / Train Operator", "contact": "9164856515", "email": "scto_shilpar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21074", "name": "KARTHIK M", "designation": "Station Controller / Train Operator", "contact": "9731107859", "email": "karthikm@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21075", "name": "PALLAVI G R", "designation": "Station Controller / Train Operator", "contact": "9036975230", "email": "pallavigr@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21076", "name": "NAVEENA M", "designation": "Station Controller / Train Operator", "contact": "7813007878", "email": "scto_naveenm@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21077", "name": "PRAKASH B R", "designation": "Station Controller / Train Operator", "contact": "9620680694", "email": "scto_prakashbr@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21078", "name": "DAYANANDA K", "designation": "Station Controller / Train Operator", "contact": "7411675816", "email": "dayanandak@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21079", "name": "ANILKUMAR KATTIMANI", "designation": "Station Controller / Train Operator", "contact": "9742708531", "email": "aprc@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21081", "name": "SINDHU N", "designation": "Station Controller / Train Operator", "contact": "9036133103", "email": "aachar.sindhu@gmail.com", "competencyExpiry": "" },
  { "id": "21082", "name": "RATHNAKUMARI", "designation": "Station Controller / Train Operator", "contact": "7259439235", "email": "rathnakumari@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21083", "name": "BHARATHI A", "designation": "Station Controller / Train Operator", "contact": "8123780996", "email": "bharathiashok90@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21084", "name": "GOWTHAMI B A", "designation": "Station Controller / Train Operator", "contact": "7411633478", "email": "gowthamiba@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21085", "name": "PADMASHREE S M", "designation": "Station Controller / Train Operator", "contact": "7411523403", "email": "padmashreesm@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21087", "name": "ASHA JAGATI", "designation": "Station Controller / Train Operator", "contact": "7892602357", "email": "ashajagati@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21088", "name": "SUMITHRA M", "designation": "Station Controller / Train Operator", "contact": "8494970254", "email": "sumithram@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21089", "name": "ASHA BAI L", "designation": "Station Controller / Train Operator", "contact": "9916518155", "email": "ashabai173@gmail.com", "competencyExpiry": "" },
  { "id": "21090", "name": "SUMAN G", "designation": "Station Controller / Train Operator", "contact": "9739250250", "email": "sumangosi@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21091", "name": "K ASHAJYOTHI", "designation": "Station Controller / Train Operator", "contact": "9591270466", "email": "ashajyothik@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21092", "name": "RADHA H G", "designation": "Station Controller / Train Operator", "contact": "7406585017", "email": "radhahg@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21093", "name": "SHRUTI", "designation": "Station Controller / Train Operator", "contact": "9900506174", "email": "shrutitegor39@gmail.com", "competencyExpiry": "" },
  { "id": "21094", "name": "BHAVYA B S", "designation": "Station Controller / Train Operator", "contact": "9740849728", "email": "Bhavyabs@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21097", "name": "SREE LATHA G", "designation": "Station Controller / Train Operator", "contact": "6360315531", "email": "ccbyph@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21098", "name": "Savitha B R", "designation": "Station Controller / Train Operator", "contact": "7411334159", "email": "savitha.vishwakarma@gmail.com", "competencyExpiry": "" },
  { "id": "21315", "name": "SHARANAPPA", "designation": "Station Controller / Train Operator", "contact": "9538975390", "email": "sharan.hanawal@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21316", "name": "MANJUNATH WARAD", "designation": "Station Controller / Train Operator", "contact": "8310128699", "email": "manjunathwarad@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21317", "name": "GOPAL MANIK", "designation": "Station Controller / Train Operator", "contact": "6366016561", "email": "gopalmanik@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21318", "name": "GOWDARA RAJASEKHAR GOWDA", "designation": "Station Controller / Train Operator", "contact": "9618418045", "email": "rajaec1991@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21319", "name": "SHASHIDHAR D G", "designation": "Station Controller / Train Operator", "contact": "8748970007", "email": "Shashi.ecmsrit@gmail.com", "competencyExpiry": "" },
  { "id": "21320", "name": "RAJESH N", "designation": "Station Controller / Train Operator", "contact": "8123920094", "email": "Rajeshn@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21322", "name": "SUNIL P", "designation": "Station Controller / Train Operator", "contact": "9686434480", "email": "sunilp@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21323", "name": "SUJAY C", "designation": "Station Controller / Train Operator", "contact": "9164813651", "email": "sujayc@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21324", "name": "NASIR AHAMED", "designation": "Station Controller / Train Operator", "contact": "7795720310", "email": "Nasir.bmrc@gmail.com", "competencyExpiry": "" },
  { "id": "21325", "name": "REVANASIDDESHA B G", "designation": "Station Controller / Train Operator", "contact": "8050066465", "email": "revanasiddesh@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21326", "name": "GOWRAPPA G RAMAKRISHNA", "designation": "Station Controller / Train Operator", "contact": "8639964107", "email": "gowrapparamakrishna@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21328", "name": "SHIVARAM.K", "designation": "Station Controller / Train Operator", "contact": "8618570188", "email": "Shivaram9341@gmail.com", "competencyExpiry": "" },
  { "id": "21329", "name": "SANAPUREDDY R L REDDY", "designation": "Station Controller / Train Operator", "contact": "9959505067", "email": "iamsrlreddy@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21330", "name": "AKHILESHA P", "designation": "Station Controller / Train Operator", "contact": "8904640492", "email": "akhileshap@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21331", "name": "DHAREPPA BHUJAPPA KALAKERI", "designation": "Station Controller / Train Operator", "contact": "9964752949", "email": "dareppa.kalkeri@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21332", "name": "SATHEESHA H N", "designation": "Station Controller / Train Operator", "contact": "9164549726", "email": "ccpyd@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21333", "name": "SHIVADHARSHAN J", "designation": "Station Controller / Train Operator", "contact": "9008021992", "email": "shivadharshanj@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21334", "name": "KRISHNA", "designation": "Station Controller / Train Operator", "contact": "9880288914", "email": "abc@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21336", "name": "RANGASWAMAIAH K", "designation": "Station Controller / Train Operator", "contact": "9590653594", "email": "rangaswamaiahk@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21337", "name": "ABHISHEK B", "designation": "Station Controller / Train Operator", "contact": "9164559643", "email": "abhishekb@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21338", "name": "MADIVALAPPA TALAKAL", "designation": "Station Controller / Train Operator", "contact": "7795617077", "email": "madivalappa@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21339", "name": "NAGAPPA HUBBALLI", "designation": "Station Controller / Train Operator", "contact": "9538735499", "email": "nagappa@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21340", "name": "REVANNA H D", "designation": "Station Controller / Train Operator", "contact": "9743871129", "email": "revannahd@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21341", "name": "SHYAM S B", "designation": "Station Controller / Train Operator", "contact": "9916314844", "email": "Shyamsb@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21342", "name": "SANDEEP M", "designation": "Station Controller / Train Operator", "contact": "7996521378", "email": "ccbyph@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21343", "name": "UMESHA S", "designation": "Station Controller / Train Operator", "contact": "7892175224", "email": "umeshas@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21344", "name": "HEMAMALA B S", "designation": "Station Controller / Train Operator", "contact": "9113820458", "email": "hemalathabs@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21345", "name": "PRASHANTHA S", "designation": "Station Controller / Train Operator", "contact": "9686321327", "email": "prasanthakspr@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21346", "name": "M V DHANANJAYA", "designation": "Station Controller / Train Operator", "contact": "7411114767", "email": "mvdhananjay@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21347", "name": "KUMARASWAMY K", "designation": "Station Controller / Train Operator", "contact": "8970805632", "email": "kumaryadav.632@gmail.com", "competencyExpiry": "" },
  { "id": "21348", "name": "SACHIN", "designation": "Station Controller / Train Operator", "contact": "9008368361", "email": "ccbyph@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21351", "name": "DEVARAJU H L", "designation": "Station Controller / Train Operator", "contact": "9740431785", "email": "scto_devarajuhl@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21352", "name": "ANILKUMAR G V", "designation": "Station Controller / Train Operator", "contact": "9008994443", "email": "anilkumargv4u@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21353", "name": "DIVYA BHARATHI M", "designation": "Station Controller / Train Operator", "contact": "8095765492", "email": "divyabharathi@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21355", "name": "SHREE HARSHITH H N", "designation": "Station Controller / Train Operator", "contact": "9972660205", "email": "Shreeharshith@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21356", "name": "PRAKASH SUBHASHCHANDRA KUMBAR", "designation": "Station Controller / Train Operator", "contact": "7829982492", "email": "kumbarprakash415@gmail.com", "competencyExpiry": "" },
  { "id": "21358", "name": "DORESWAMY", "designation": "Station Controller / Train Operator", "contact": "9740998309", "email": "doreswamy@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21359", "name": "MANJUNATHA K C", "designation": "Station Controller / Train Operator", "contact": "9900620143", "email": "manjunatha.kc2@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21360", "name": "SUMANA SHANTHA RAM", "designation": "Station Controller / Train Operator", "contact": "7975868710", "email": "sumanaganga@gmail.com", "competencyExpiry": "" },
  { "id": "21361", "name": "MANJUNATH M", "designation": "Station Controller / Train Operator", "contact": "9738764075", "email": "manjumadhava@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21362", "name": "SHARANABASAPPA", "designation": "Station Controller / Train Operator", "contact": "8050124670", "email": "Sharanabasappa_scto@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21363", "name": "RAHUL CHAVAN", "designation": "Station Controller / Train Operator", "contact": "9591914149", "email": "rahulchavan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21364", "name": "BASAYYA HIREMATH", "designation": "Station Controller / Train Operator", "contact": "9972073198", "email": "basuhiremath@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21366", "name": "SHARANABASAPPA", "designation": "Station Controller / Train Operator", "contact": "9686495493", "email": "ccpyd@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21367", "name": "KARUNAKARAN B", "designation": "Station Controller / Train Operator", "contact": "8553022630", "email": "bhimraj_kk@yahoo.com", "competencyExpiry": "" },
  { "id": "21368", "name": "MUZAMMIL TATTIPURI", "designation": "Station Controller / Train Operator", "contact": "9972694548", "email": "muzammilvt@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21370", "name": "NIJALINGAPPA H", "designation": "Station Controller / Train Operator", "contact": "8867844139", "email": "nijalingappah@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21371", "name": "BALAJI", "designation": "Station Controller / Train Operator", "contact": "8197464699", "email": "rathodbalajiec@gmail.com", "competencyExpiry": "" },
  { "id": "21372", "name": "HARISH BABU T V", "designation": "Station Controller / Train Operator", "contact": "9611925151", "email": "harishbabutv@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21373", "name": "M.MANOJKUMAR", "designation": "Station Controller / Train Operator", "contact": "9741863648", "email": "to_mmkumar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21374", "name": "SADANANDA DEVADIGA", "designation": "Station Controller / Train Operator", "contact": "9743864803", "email": "Sadaupp7@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21376", "name": "AJITH K.S.", "designation": "Station Controller / Train Operator", "contact": "8310929086", "email": "ajithks@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21377", "name": "MOHAN C.", "designation": "Station Controller / Train Operator", "contact": "7353325530", "email": "mohancd91@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21378", "name": "MANOHAR D.R.", "designation": "Station Controller / Train Operator", "contact": "9060018057", "email": "mahardr17@gmail.com", "competencyExpiry": "" },
  { "id": "21379", "name": "UDAYA P.", "designation": "Station Controller / Train Operator", "contact": "8861883961", "email": "nijalingappah@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21380", "name": "SRIJAN PUTHRAN", "designation": "Station Controller / Train Operator", "contact": "8660603844", "email": "sri.puthran.16@gmail.com", "competencyExpiry": "" },
  { "id": "21381", "name": "RAVIKIRAN MALAKAJAPPA BETAGERI", "designation": "Station Controller / Train Operator", "contact": "9902516485", "email": "ravikiranbetageri025@gmail.com", "competencyExpiry": "" },
  { "id": "21382", "name": "SHASHIKUMAR M.", "designation": "Station Controller / Train Operator", "contact": "7975923443", "email": "shashikumar.m@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21383", "name": "YOGEESH G S", "designation": "Station Controller / Train Operator", "contact": "8970364677", "email": "yogeeshgs@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21386", "name": "SHIVAKUMAR H.", "designation": "Station Controller / Train Operator", "contact": "9164829839", "email": "shivakumarh@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21414", "name": "Harsha.N", "designation": "Station Controller / Train Operator", "contact": "9480550551", "email": "nharsha@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21416", "name": "Amithkumar V", "designation": "Station Controller / Train Operator", "contact": "7760390864", "email": "amithkumarv@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21418", "name": "MANJUNATH PUJARI", "designation": "Station Controller / Train Operator", "contact": "8971007579", "email": "manjunath_cp@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21419", "name": "Nagendran J", "designation": "Station Controller / Train Operator", "contact": "9686836808", "email": "nagendranJ@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21420", "name": "GANESHA K M", "designation": "Station Controller / Train Operator", "contact": "8197387372", "email": "ganeshakm@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21422", "name": "Gautham.B.K", "designation": "Station Controller / Train Operator", "contact": "9845857315", "email": "gautham.bk@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21424", "name": "Shivamurthy Naik p", "designation": "Station Controller / Train Operator", "contact": "8884542197", "email": "shivamurthynaikp@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21425", "name": "LATHESH S AMIN", "designation": "Station Controller / Train Operator", "contact": "9901375971", "email": "latheshamin@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21426", "name": "Ganapati", "designation": "Station Controller / Train Operator", "contact": "9663092360", "email": "ganapati@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21427", "name": "ABHINANDA D S", "designation": "Station Controller / Train Operator", "contact": "9535967962", "email": "abhinandads@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21428", "name": "Arpitha M S", "designation": "Station Controller / Train Operator", "contact": "7892605970", "email": "arpithams2@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21429", "name": "sharanabasu sonna", "designation": "Station Controller / Train Operator", "contact": "9972603361", "email": "Sharanabasusonna@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21430", "name": "krishna murthy v", "designation": "Station Controller / Train Operator", "contact": "7019472154", "email": "krishnamurthyv@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21431", "name": "Shared Ameenasa Nadaf", "designation": "Station Controller / Train Operator", "contact": "8971173681", "email": "shareef@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21433", "name": "Maruthi h", "designation": "Station Controller / Train Operator", "contact": "9740255941", "email": "Maruthi@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21434", "name": "PRUTHVIRAJ L K", "designation": "Station Controller / Train Operator", "contact": "8088821541", "email": "pruthviraj@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21435", "name": "JAGADEESHA", "designation": "Station Controller / Train Operator", "contact": "8073976782", "email": "jagadeesha_bn@yahoo.com", "competencyExpiry": "" },
  { "id": "21436", "name": "MANJUNATHA K R", "designation": "Station Controller / Train Operator", "contact": "9916984731", "email": "manjunatha.kr@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21437", "name": "PITCHUKA SIVALEELA", "designation": "Station Controller / Train Operator", "contact": "7618711764", "email": "sivaleelaece@gmail.com", "competencyExpiry": "" },
  { "id": "21438", "name": "DIVYAMANI H D", "designation": "Station Controller / Train Operator", "contact": "7676079994", "email": "divyamanihd@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21439", "name": "Mamatha T.V.", "designation": "Station Controller / Train Operator", "contact": "9743040146", "email": "Mamathatv@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21440", "name": "Salman H", "designation": "Station Controller / Train Operator", "contact": "9845583650", "email": "salmanh@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21441", "name": "Lalasab", "designation": "Station Controller / Train Operator", "contact": "9902533506", "email": "scto_lalsab@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21442", "name": "Hemanthkumar M L", "designation": "Station Controller / Train Operator", "contact": "9986232467", "email": "hemanthkumarml@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21443", "name": "IRFAN V", "designation": "Station Controller / Train Operator", "contact": "9739408007", "email": "irfanv78@gmail.com", "competencyExpiry": "" },
  { "id": "21444", "name": "SIDDARAMA", "designation": "Station Controller / Train Operator", "contact": "9964613522", "email": "siddarama@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21448", "name": "Shashirekha B R", "designation": "Station Controller / Train Operator", "contact": "7760411752", "email": "shashirekhabr007@gmail.com", "competencyExpiry": "" },
  { "id": "21449", "name": "Bhavya KN", "designation": "Station Controller / Train Operator", "contact": "9591611861", "email": "bhavyakn@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21450", "name": "RAMACHANDRAN L", "designation": "Station Controller / Train Operator", "contact": "9480517260", "email": "ramachandranl@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21452", "name": "Mamatha B N", "designation": "Station Controller / Train Operator", "contact": "9686108564", "email": "mamathabn@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21453", "name": "MAHANINGAPPA S CHAKKADI", "designation": "Station Controller / Train Operator", "contact": "9591576841", "email": "mahaningappaschakkadi@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21454", "name": "LATHA S", "designation": "Station Controller / Train Operator", "contact": "9845167982", "email": "slatha@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21455", "name": "NANDEESH KUMAR", "designation": "Station Controller / Train Operator", "contact": "9901740229", "email": "nandeeshkumarm@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21457", "name": "Jayashree Goudar", "designation": "Station Controller / Train Operator", "contact": "7204608396", "email": "jayashreegoudar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21458", "name": "Sowmya E", "designation": "Station Controller / Train Operator", "contact": "9036902067", "email": "Esowmya@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21459", "name": "Navaneetha Madhu", "designation": "Station Controller / Train Operator", "contact": "9449749739", "email": "navaneethamadhu@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21460", "name": "Kavitha M N", "designation": "Station Controller / Train Operator", "contact": "9036109108", "email": "kavithajain30@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21461", "name": "Kavya.G", "designation": "Station Controller / Train Operator", "contact": "9686428872", "email": "kavyag@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21463", "name": "Manjuvani S V", "designation": "Station Controller / Train Operator", "contact": "9972748147", "email": "ccbyph@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21464", "name": "Anusha S", "designation": "Station Controller / Train Operator", "contact": "7483126095", "email": "pyid@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21465", "name": "MANGALGOURI KITTUR", "designation": "Station Controller / Train Operator", "contact": "9972346202", "email": "mangalgouri@gmail.com", "competencyExpiry": "" },
  { "id": "21466", "name": "UMALATHA B S", "designation": "Station Controller / Train Operator", "contact": "9742164169", "email": "umalathabs@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21467", "name": "Kavitha G.K", "designation": "Station Controller / Train Operator", "contact": "9019954400", "email": "kavithagk@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21468", "name": "Girish V", "designation": "Station Controller / Train Operator", "contact": "9686165508", "email": "girishvappu66@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21469", "name": "U.Roopa", "designation": "Station Controller / Train Operator", "contact": "8792294140", "email": "roopa_usurupati@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21470", "name": "Latha R", "designation": "Station Controller / Train Operator", "contact": "7676063893", "email": "latha@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21471", "name": "Divyashree H M", "designation": "Station Controller / Train Operator", "contact": "8147214691", "email": "divyashreehm@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21472", "name": "VIDYA B R", "designation": "Station Controller / Train Operator", "contact": "9148793521", "email": "vidyathanu1@gmail.com", "competencyExpiry": "" },
  { "id": "21473", "name": "Rakshitha M K", "designation": "Station Controller / Train Operator", "contact": "8549952552", "email": "rakshitha.mk@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21474", "name": "Pooja.N", "designation": "Station Controller / Train Operator", "contact": "8553327904", "email": "poojan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21475", "name": "Sukanya s", "designation": "Station Controller / Train Operator", "contact": "9741953749", "email": "Rosysukanya410@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21476", "name": "Smitha.R", "designation": "Station Controller / Train Operator", "contact": "9742750407", "email": "ccpyid@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21477", "name": "Prarthana chinmayee CM", "designation": "Station Controller / Train Operator", "contact": "9742045296", "email": "prarthana.chinmayee@gmail.com", "competencyExpiry": "" },
  { "id": "21478", "name": "Yashaswini CT", "designation": "Station Controller / Train Operator", "contact": "9739948352", "email": "yashaswini.ct@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21479", "name": "BHAVYA N", "designation": "Station Controller / Train Operator", "contact": "8197047892", "email": "bhavyan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21480", "name": "Vinutha V B", "designation": "Station Controller / Train Operator", "contact": "9738714456", "email": "vinuthavb@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21481", "name": "SHRUTHI H J", "designation": "Station Controller / Train Operator", "contact": "8748800562", "email": "shruthihj@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21482", "name": "DEVARAJ B", "designation": "Station Controller / Train Operator", "contact": "9591155756", "email": "devrajb@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21483", "name": "Priyanka Patil", "designation": "Station Controller / Train Operator", "contact": "8147184542", "email": "priyankapatil@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21484", "name": "Anita Irappa Aikur", "designation": "Station Controller / Train Operator", "contact": "7411856595", "email": "scto_anitaia@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21485", "name": "Shilparani", "designation": "Station Controller / Train Operator", "contact": "8722999572", "email": "shilpademshetty@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21486", "name": "lakshmi", "designation": "Station Controller / Train Operator", "contact": "9740879035", "email": "lakshmivasudevan323@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21487", "name": "Divya A", "designation": "Station Controller / Train Operator", "contact": "9916136120", "email": "divyaachut@gmail.com", "competencyExpiry": "" },
  { "id": "21488", "name": "Ashwini Awati", "designation": "Station Controller / Train Operator", "contact": "7411103715", "email": "ashwiniawati@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21489", "name": "Arpitha K S", "designation": "Station Controller / Train Operator", "contact": "9731069713", "email": "arpithaks@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21490", "name": "Kumari Shailaja Bashetty", "designation": "Station Controller / Train Operator", "contact": "8792550331", "email": "shailajabashetty@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21491", "name": "Bhavya S S", "designation": "Station Controller / Train Operator", "contact": "9535097369", "email": "bhavyashankarappa@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21492", "name": "Smitha.M.Revanakar", "designation": "Station Controller / Train Operator", "contact": "8884961399", "email": "smithamr@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21494", "name": "Shashikala", "designation": "Station Controller / Train Operator", "contact": "6362228337", "email": "Shashikala@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21495", "name": "Anjana R", "designation": "Station Controller / Train Operator", "contact": "8123390571", "email": "anjanar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21496", "name": "Sumalatha D Naik", "designation": "Station Controller / Train Operator", "contact": "9742965000", "email": "sumalathad@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21497", "name": "Varalakshmi N", "designation": "Station Controller / Train Operator", "contact": "9845936215", "email": "ccbyph@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21498", "name": "Savitha N", "designation": "Station Controller / Train Operator", "contact": "8123696997", "email": "savithan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21500", "name": "Mamata Gayakavad", "designation": "Station Controller / Train Operator", "contact": "8861241190", "email": "mamatagt@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21501", "name": "Lavanya B R", "designation": "Station Controller / Train Operator", "contact": "7353535139", "email": "Lavanyabr@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21502", "name": "Seema Subhan", "designation": "Station Controller / Train Operator", "contact": "9739827133", "email": "subhan_seema@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21504", "name": "Bhagyalakshmi.V", "designation": "Station Controller / Train Operator", "contact": "8123151307", "email": "bhagya.hsv@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21505", "name": "Priyanka Ballary", "designation": "Station Controller / Train Operator", "contact": "9986092470", "email": "priyankab@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21506", "name": "Chikke gowda N", "designation": "Station Controller / Train Operator", "contact": "7760405323", "email": "nchikkegowda99@gmail.com", "competencyExpiry": "" },
  { "id": "21507", "name": "SHIVA KUMAR B", "designation": "Station Controller / Train Operator", "contact": "9986178077", "email": "shivakumarb@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21508", "name": "MUTHANNA K.B", "designation": "Station Controller / Train Operator", "contact": "9480948853", "email": "muthannakb@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21509", "name": "ONKARAPPA L", "designation": "Station Controller / Train Operator", "contact": "9481555338", "email": "onkarappa@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21694", "name": "Nagendra C S", "designation": "Station Controller / Train Operator", "contact": "8971071041", "email": "nagendracs@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21695", "name": "Muragesh Dharigoudar", "designation": "Station Controller / Train Operator", "contact": "7411505585", "email": "murugeshdharigoudar@hotmail.com", "competencyExpiry": "" },
  { "id": "21696", "name": "Manjunatha S", "designation": "Station Controller / Train Operator", "contact": "8792357209", "email": "manjunaths@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21697", "name": "PURUSHOTHAM N S", "designation": "Station Controller / Train Operator", "contact": "7760857701", "email": "Purushothamns@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21699", "name": "Thirtha Prasad. B", "designation": "Station Controller / Train Operator", "contact": "9738363485", "email": "thirthaprasad@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21700", "name": "K Viswanath", "designation": "Station Controller / Train Operator", "contact": "9908849744", "email": "kenchalaviswanath@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21701", "name": "Ravikumar", "designation": "Station Controller / Train Operator", "contact": "9742211549", "email": "ravikumarveeraiah@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21702", "name": "Chandrashekar G", "designation": "Station Controller / Train Operator", "contact": "8553502673", "email": "Chandrashekarg@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21703", "name": "Srinivas V", "designation": "Station Controller / Train Operator", "contact": "9035991917", "email": "srinivas.v@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21704", "name": "Manoj Rathod", "designation": "Station Controller / Train Operator", "contact": "9902592050", "email": "majvrathod@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21705", "name": "Dhanaraj D", "designation": "Station Controller / Train Operator", "contact": "8867174557", "email": "dhanarajd@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21706", "name": "Gourishankar.M.Handi", "designation": "Station Controller / Train Operator", "contact": "9538585823", "email": "gourishmh12@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21707", "name": "Harish G", "designation": "Station Controller / Train Operator", "contact": "9590792958", "email": "hariin8086@gmail.com", "competencyExpiry": "" },
  { "id": "21708", "name": "SOWMYA N", "designation": "Station Controller / Train Operator", "contact": "8050628087", "email": "sowmyan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21709", "name": "Priyanka P", "designation": "Station Controller / Train Operator", "contact": "9591754013", "email": "murugeshpd@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21711", "name": "Shakuntala", "designation": "Station Controller / Train Operator", "contact": "7022328078", "email": "shakuntala@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21712", "name": "Hemavathi J", "designation": "Station Controller / Train Operator", "contact": "8892420906", "email": "jhemavathi@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21713", "name": "Sheeba Supritha S", "designation": "Station Controller / Train Operator", "contact": "6360904129", "email": "sheebasupritha@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21714", "name": "Priyanka K N", "designation": "Station Controller / Train Operator", "contact": "8105262671", "email": "priyankakn@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21715", "name": "RADHIKA M", "designation": "Station Controller / Train Operator", "contact": "9980129404", "email": "radhika_m@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21716", "name": "Sadika Pathan", "designation": "Station Controller / Train Operator", "contact": "9008448527", "email": "sadikapathan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21717", "name": "Sowmyashree B", "designation": "Station Controller / Train Operator", "contact": "9739543373", "email": "sowmyabraj1993@gmail.com", "competencyExpiry": "" },
  { "id": "21718", "name": "Baby", "designation": "Station Controller / Train Operator", "contact": "9538921886", "email": "annaiahbaby@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21719", "name": "Rashmitha D", "designation": "Station Controller / Train Operator", "contact": "8548939772", "email": "rashmitha_d@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21720", "name": "ANAND KUMAR", "designation": "Station Controller / Train Operator", "contact": "9113277720", "email": "scto_anandkumar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21721", "name": "Shabanajmi", "designation": "Station Controller / Train Operator", "contact": "9916146678", "email": "shabanajmi@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21722", "name": "Sharanabasappa patil", "designation": "Station Controller / Train Operator", "contact": "9738717773", "email": "Sharanabasappa.b.patil@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21723", "name": "MANJUNATH", "designation": "Station Controller / Train Operator", "contact": "8861140447", "email": "manjureddy@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21724", "name": "Anand M", "designation": "Station Controller / Train Operator", "contact": "9538513860", "email": "anandm.828@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21725", "name": "Soumya Patil", "designation": "Station Controller / Train Operator", "contact": "8884546996", "email": "soumyapatil@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21944", "name": "Kishore S K", "designation": "Station Controller / Train Operator", "contact": "9916666273", "email": "21944@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21945", "name": "Nithin Kumar M", "designation": "Station Controller / Train Operator", "contact": "9632326573", "email": "nithin_m@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21946", "name": "Ratheesh T E", "designation": "Station Controller / Train Operator", "contact": "9656025479", "email": "ratheesh@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21947", "name": "Deepesh K", "designation": "Station Controller / Train Operator", "contact": "7034502967", "email": "deepesh@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21950", "name": "Dheerej B", "designation": "Station Controller / Train Operator", "contact": "9405254521", "email": "dheerej@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21953", "name": "Raveen G", "designation": "Station Controller / Train Operator", "contact": "8921777345", "email": "raveengopalakrishnan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21954", "name": "Prasad S", "designation": "Station Controller / Train Operator", "contact": "9964269787", "email": "yadav.sprasad@yahoo.in", "competencyExpiry": "" },
  { "id": "21955", "name": "Ashish Kumar", "designation": "Station Controller / Train Operator", "contact": "7063965909", "email": "ashishkumar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21959", "name": "Kanchanapalli Nagesh", "designation": "Station Controller / Train Operator", "contact": "9018788557", "email": "Nagesharmy@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21960", "name": "Linga Reddy R", "designation": "Station Controller / Train Operator", "contact": "9440650472", "email": "rddy_rl@yahoo.co.in", "competencyExpiry": "" },
  { "id": "21961", "name": "Santhosh Kumara A T", "designation": "Station Controller / Train Operator", "contact": "8088944848", "email": "itsupport@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21962", "name": "Sathya Kumar D", "designation": "Station Controller / Train Operator", "contact": "", "email": "Suvarna395@gmail.com", "competencyExpiry": "" },
  { "id": "21963", "name": "K Suresh Babu", "designation": "Station Controller / Train Operator", "contact": "8082009869", "email": "ksb.kolasuresh@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21964", "name": "Ramesh K", "designation": "Station Controller / Train Operator", "contact": "9066861458", "email": "ramgee358@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21965", "name": "Chandra Rao Bongu", "designation": "Station Controller / Train Operator", "contact": "9205001503", "email": "chandraraobongu@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21966", "name": "Jai Ganesh G", "designation": "Station Controller / Train Operator", "contact": "8147114700", "email": "jaiganeshg@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21967", "name": "Mahesh Rao Kale R", "designation": "Station Controller / Train Operator", "contact": "9958153876", "email": "maheshraokale@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21968", "name": "M Venkata Kiran Kumar", "designation": "Station Controller / Train Operator", "contact": "8597547949", "email": "manasakiran369@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21969", "name": "Jeeva S", "designation": "Station Controller / Train Operator", "contact": "8218123370", "email": "jeevas@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21970", "name": "Syama Raju M", "designation": "Station Controller / Train Operator", "contact": "8099018080", "email": "syamraj19831983@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21971", "name": "Vinaykumar", "designation": "Station Controller / Train Operator", "contact": "8790101259", "email": "vinay1642@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21972", "name": "Mahaboob Basha Shaik", "designation": "Station Controller / Train Operator", "contact": "9531151020", "email": "mahaboobbasha@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21973", "name": "A Thirunarayan Murthy", "designation": "Station Controller / Train Operator", "contact": "7204479520", "email": "thirunarayanmurthya@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21974", "name": "Sankar M", "designation": "Station Controller / Train Operator", "contact": "8789948068", "email": "sankar1663@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21975", "name": "Nithin K P", "designation": "Station Controller / Train Operator", "contact": "9400910542", "email": "nithinkp@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21976", "name": "Mahesha B", "designation": "Station Controller / Train Operator", "contact": "9740147996", "email": "xyz@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21977", "name": "Siva Nag Kakarla V Satya", "designation": "Station Controller / Train Operator", "contact": "8919538321", "email": "shivanag42@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21978", "name": "Rangaswamy D N", "designation": "Station Controller / Train Operator", "contact": "8310992464", "email": "rangaswamydn@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21979", "name": "Ramesh Nadagaddi", "designation": "Station Controller / Train Operator", "contact": "9971190134", "email": "rameshnadagaddi@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21980", "name": "Metta Kameswara Rao", "designation": "Station Controller / Train Operator", "contact": "8901570928", "email": "krmettacherry@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21981", "name": "Shiva Kumar Hanumanthappa", "designation": "Station Controller / Train Operator", "contact": "7339586416", "email": "shivakumar1712@bmrc.co.in", "competencyExpiry": "" },
  { "id": "21982", "name": "Hari Kishan Chodavarapu", "designation": "Station Controller / Train Operator", "contact": "7013587508", "email": "harikishan@bmrc.co.in", "competencyExpiry": "" },
  { "id": "22222", "name": "Sonu Kumar Jha", "designation": "Station Controller / Train Operator", "contact": "9958462451", "email": "sonubjha@gmail.com", "competencyExpiry": "" },
  { "id": "22224", "name": "Sunil Kumar Satpathy", "designation": "Station Controller / Train Operator", "contact": "7347031505", "email": "sunilmayoon@gmail.com", "competencyExpiry": "" },
  { "id": "22225", "name": "Manoj Cb", "designation": "Station Controller / Train Operator", "contact": "9446007736", "email": "majcb73@gmail.com", "competencyExpiry": "" },
  { "id": "22226", "name": "Shiva Kant Gaur", "designation": "Station Controller / Train Operator", "contact": "9149707001", "email": "shivakantgaur@gmail.com", "competencyExpiry": "" },
  { "id": "22227", "name": "G A Sudhakar", "designation": "Station Controller / Train Operator", "contact": "9482671753", "email": "sudhakarga@bmrc.co.in", "competencyExpiry": "" },
  { "id": "22228", "name": "Sateesh Kumar Choppara", "designation": "Station Controller / Train Operator", "contact": "9866037178", "email": "sckumar127@gmail.com", "competencyExpiry": "" },
  { "id": "22229", "name": "G Raja", "designation": "Station Controller / Train Operator", "contact": "9488779704", "email": "graja@bmrc.co.in", "competencyExpiry": "" },
  { "id": "22230", "name": "Balahari N", "designation": "Station Controller / Train Operator", "contact": "8867806398", "email": "balaharikrishna9@gmail.com", "competencyExpiry": "" },
  { "id": "22231", "name": "Manju B G", "designation": "Station Controller / Train Operator", "contact": "9113929180", "email": "manjubg927@gmail.com", "competencyExpiry": "" },
  { "id": "22234", "name": "Girikumar G", "designation": "Station Controller / Train Operator", "contact": "9571979380", "email": "girikumar70593@gmail.com", "competencyExpiry": "" },
  { "id": "22235", "name": "Nissam S", "designation": "Station Controller / Train Operator", "contact": "9995097034", "email": "nissam85@gmail.com", "competencyExpiry": "" },
  { "id": "22236", "name": "Ravindra Sahu", "designation": "Station Controller / Train Operator", "contact": "7406637825", "email": "RSAHU.CHAIL@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22237", "name": "Ranjan Kumar Bharati", "designation": "Station Controller / Train Operator", "contact": "9957991707", "email": "branjanb786@gmail.com", "competencyExpiry": "" },
  { "id": "22239", "name": "Manjunatha K S", "designation": "Station Controller / Train Operator", "contact": "9353547114", "email": "manvikgowda118@gmail.com", "competencyExpiry": "" },
  { "id": "22240", "name": "Sunil PN", "designation": "Station Controller / Train Operator", "contact": "8861947914", "email": "SUNILNANDAPPA@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22241", "name": "Beer Bhagat Singh", "designation": "Station Controller / Train Operator", "contact": "9848723443", "email": "PREM4U1984@REDIFFMAIL.COM", "competencyExpiry": "" },
  { "id": "22242", "name": "Anil Kumar Patchipala", "designation": "Station Controller / Train Operator", "contact": "8288902568", "email": "bangarraju.300@gmail.com", "competencyExpiry": "" },
  { "id": "22243", "name": "Manish Ranjan", "designation": "Station Controller / Train Operator", "contact": "9821761151", "email": "manishranjan193@gmail.com", "competencyExpiry": "" },
  { "id": "22244", "name": "Ravi H R", "designation": "Station Controller / Train Operator", "contact": "8275485843", "email": "ravijathin1608@gmail.com", "competencyExpiry": "" },
  { "id": "22245", "name": "Shamukharao Bokam", "designation": "Station Controller / Train Operator", "contact": "9030137358", "email": "shamukharao.rao@gmail.com", "competencyExpiry": "" },
  { "id": "22246", "name": "Bijay Kumar Singh", "designation": "Station Controller / Train Operator", "contact": "8295330140", "email": "BIJAYSINGH0103@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22247", "name": "Ramesh", "designation": "Station Controller / Train Operator", "contact": "7076121965", "email": "rameshachari2009@gmail.com", "competencyExpiry": "" },
  { "id": "22248", "name": "Raghavaraju Ramesh", "designation": "Station Controller / Train Operator", "contact": "9986093337", "email": "ramesh.raghavaraju0304@gmail.com", "competencyExpiry": "" },
  { "id": "22249", "name": "M Srikanth Reddy", "designation": "Station Controller / Train Operator", "contact": "9502329922", "email": "srikanth232reddy@gmail.com", "competencyExpiry": "" },
  { "id": "22250", "name": "Krishna Prasad K", "designation": "Station Controller / Train Operator", "contact": "8136916628", "email": "krishna.kp286@gmail.com", "competencyExpiry": "" },
  { "id": "22251", "name": "Kalakara Mahanta", "designation": "Station Controller / Train Operator", "contact": "7906553219", "email": "kalakarmahanta904@gmail.com", "competencyExpiry": "" },
  { "id": "22254", "name": "Kc Abhilash", "designation": "Station Controller / Train Operator", "contact": "8447548871", "email": "abhinambiar29@gmail.com", "competencyExpiry": "" },
  { "id": "22255", "name": "Sudhakar S", "designation": "Station Controller / Train Operator", "contact": "8618233142", "email": "sudhakar.roshini4756@gmail.com", "competencyExpiry": "" },
  { "id": "22256", "name": "Siddalingaswamy J", "designation": "Station Controller / Train Operator", "contact": "9980924776", "email": "siddalingaswamyswamy@bmrc.co.in", "competencyExpiry": "" },
  { "id": "22257", "name": "Sridhar N", "designation": "Station Controller / Train Operator", "contact": "8811877811", "email": "sridharnakkur81@gmail.com", "competencyExpiry": "" },
  { "id": "22258", "name": "Sankara Rao Achyutha", "designation": "Station Controller / Train Operator", "contact": "7075556600", "email": "sankararaoachyutha@gmail.com", "competencyExpiry": "" },
  { "id": "22259", "name": "Suresh Kumar S", "designation": "Station Controller / Train Operator", "contact": "9632520695", "email": "Sureshkumaramma5892@gmail.com", "competencyExpiry": "" },
  { "id": "22260", "name": "Satya Prakash", "designation": "Station Controller / Train Operator", "contact": "7903140344", "email": "spndl06@gmail.com", "competencyExpiry": "" },
  { "id": "22261", "name": "Babu Halakarni", "designation": "Station Controller / Train Operator", "contact": "8310301779", "email": "halakarnibabu@gmail.com", "competencyExpiry": "" },
  { "id": "22262", "name": "Siliveru Nagabrahmam", "designation": "Station Controller / Train Operator", "contact": "6281704714", "email": "brahmam2628@gmail.com", "competencyExpiry": "" },
  { "id": "22263", "name": "Siddappa Revakkanavar", "designation": "Station Controller / Train Operator", "contact": "8088519325", "email": "siddappar@bmrc.co.in", "competencyExpiry": "" },
  { "id": "22264", "name": "Yashodhar Kl", "designation": "Station Controller / Train Operator", "contact": "9108529171", "email": "yeshu.kattemane@gmail.com", "competencyExpiry": "" },
  { "id": "22265", "name": "Lakshmana Rao Akuru", "designation": "Station Controller / Train Operator", "contact": "9649016589", "email": "wonderboy.raghu@gmail.com", "competencyExpiry": "" },
  { "id": "22266", "name": "Raj Kishor", "designation": "Station Controller / Train Operator", "contact": "7338521402", "email": "rajkishor835@gmail.com", "competencyExpiry": "" },
  { "id": "22268", "name": "Shantha Murthy G", "designation": "Station Controller / Train Operator", "contact": "9686237294", "email": "karnmurthy@gmail.com", "competencyExpiry": "" },
  { "id": "22269", "name": "Akhilesh Kumar", "designation": "Station Controller / Train Operator", "contact": "8136088358", "email": "akhileshbarnwal05@gmail.com", "competencyExpiry": "" },
  { "id": "22271", "name": "K Pardhasaradhi", "designation": "Station Controller / Train Operator", "contact": "7508850298", "email": "saradhi811@gmail.com", "competencyExpiry": "" },
  { "id": "22274", "name": "Arunald Lezly F", "designation": "Station Controller / Train Operator", "contact": "7404668817", "email": "arunald30@gmail.com", "competencyExpiry": "" },
  { "id": "22275", "name": "Kiran Kumar Angala", "designation": "Station Controller / Train Operator", "contact": "8435043011", "email": "angalakk@gmail.com", "competencyExpiry": "" },
  { "id": "22276", "name": "M A John William", "designation": "Station Controller / Train Operator", "contact": "9990088056", "email": "jw42553@gmail.com", "competencyExpiry": "" },
  { "id": "22277", "name": "Unnikrishnan K", "designation": "Station Controller / Train Operator", "contact": "8729924204", "email": "uknair29@gmail.com", "competencyExpiry": "" },
  { "id": "22278", "name": "Mahesh K T", "designation": "Station Controller / Train Operator", "contact": "6282419131", "email": "maheshputhiyottil@gmail.com", "competencyExpiry": "" },
  { "id": "22279", "name": "Suresh Kumar B", "designation": "Station Controller / Train Operator", "contact": "8610944934", "email": "sureshbalaraman2012@gmail.com", "competencyExpiry": "" },
  { "id": "22280", "name": "Ratheesh Raj R", "designation": "Station Controller / Train Operator", "contact": "8547338899", "email": "ratheeshrajr@gmail.com", "competencyExpiry": "" },
  { "id": "22281", "name": "Ashok Itnal", "designation": "Station Controller / Train Operator", "contact": "7417312616", "email": "itnalashok994@gmail.com", "competencyExpiry": "" },
  { "id": "22282", "name": "Vinod Kumar Singh V", "designation": "Station Controller / Train Operator", "contact": "9481803433", "email": "vidsingh1984@yahoo.com", "competencyExpiry": "" },
  { "id": "22283", "name": "Sivaprakasam G", "designation": "Station Controller / Train Operator", "contact": "8248639313", "email": "shivaprakasam1982@gmail.com", "competencyExpiry": "" },
  { "id": "22284", "name": "Aravinda Vinod Kumar.B", "designation": "Station Controller / Train Operator", "contact": "7975825767", "email": "arvind.b@bmrc.co.in", "competencyExpiry": "" },
  { "id": "22286", "name": "J Ebnezer Navaraj", "designation": "Station Controller / Train Operator", "contact": "7847805614", "email": "ebenezernavaraj12@gmail.com", "competencyExpiry": "" },
  { "id": "22287", "name": "Suresh Sanakall", "designation": "Station Controller / Train Operator", "contact": "9448651205", "email": "sureshsanakall1983@gmail.com", "competencyExpiry": "" },
  { "id": "22288", "name": "Basuki Prasad Das", "designation": "Station Controller / Train Operator", "contact": "9900946085", "email": "basuki7751@gmail.com", "competencyExpiry": "" },
  { "id": "22289", "name": "Sanjay Kumar", "designation": "Station Controller / Train Operator", "contact": "9738125019", "email": "AYUBI12311@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22290", "name": "D Suresh", "designation": "Station Controller / Train Operator", "contact": "7760224464", "email": "suresh06sy@gmail.com", "competencyExpiry": "" },
  { "id": "22291", "name": "Preejith Chandran", "designation": "Station Controller / Train Operator", "contact": "8281963669", "email": "preejith153@gmail.com", "competencyExpiry": "" },
  { "id": "22294", "name": "Viswanath K S", "designation": "Station Controller / Train Operator", "contact": "8837571105", "email": "visv77@gmail.com", "competencyExpiry": "" },
  { "id": "22295", "name": "Pradeep R", "designation": "Station Controller / Train Operator", "contact": "8095862578", "email": "pradeepraj.raj04@gmail.com", "competencyExpiry": "" },
  { "id": "22296", "name": "Sooraj R", "designation": "Station Controller / Train Operator", "contact": "7892500637", "email": "rsooraj132@gmail.com", "competencyExpiry": "" },
  { "id": "22297", "name": "Mohammed Rafiq Mulla", "designation": "Station Controller / Train Operator", "contact": "8875426277", "email": "mohdrafiq737@gmail.com", "competencyExpiry": "" },
  { "id": "22307", "name": "Ramsingh J", "designation": "Station Controller / Train Operator", "contact": "9901808656", "email": "ramsinghj0582@gmail.com", "competencyExpiry": "" },
  { "id": "22308", "name": "Rajesh K A", "designation": "Station Controller / Train Operator", "contact": "8901084687", "email": "rajeshka04061979@gmail.com", "competencyExpiry": "" },
  { "id": "22309", "name": "Madiraju Kiran", "designation": "Station Controller / Train Operator", "contact": "9032972851", "email": "KIRAN.MADIRAJU10@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22310", "name": "Shyju K V", "designation": "Station Controller / Train Operator", "contact": "9695685364", "email": "mail2shyjukv@gmail.com", "competencyExpiry": "" },
  { "id": "22312", "name": "Jagadeesha K S", "designation": "Station Controller / Train Operator", "contact": "9845565016", "email": "jagadeesh1467@gmail.com", "competencyExpiry": "" },
  { "id": "22313", "name": "Senthil K", "designation": "Station Controller / Train Operator", "contact": "7598372649", "email": "senthil.pavesh@gmail.com", "competencyExpiry": "" },
  { "id": "22314", "name": "Vinoth Raj J", "designation": "Station Controller / Train Operator", "contact": "8884121106", "email": "vithr925@gmail.com", "competencyExpiry": "" },
  { "id": "22315", "name": "Krishna Murthy R", "designation": "Station Controller / Train Operator", "contact": "9682587808", "email": "krishna.pav111@gmail.com", "competencyExpiry": "" },
  { "id": "22316", "name": "A Dinesh Kumar", "designation": "Station Controller / Train Operator", "contact": "7253944283", "email": "dinubharathi1@gmail.com", "competencyExpiry": "" },
  { "id": "22317", "name": "Naresh Bana", "designation": "Station Controller / Train Operator", "contact": "7087675057", "email": "nareshbana108@gmail.com", "competencyExpiry": "" },
  { "id": "22318", "name": "Srinivasa Rao Naira", "designation": "Station Controller / Train Operator", "contact": "8427850889", "email": "srinivasnaira24@gmail.com", "competencyExpiry": "" },
  { "id": "22319", "name": "Prakash P", "designation": "Station Controller / Train Operator", "contact": "9160653184", "email": "prakash.p5613.pp@gmail.com", "competencyExpiry": "" },
  { "id": "22320", "name": "Rajashekhara G K", "designation": "Station Controller / Train Operator", "contact": "9632587820", "email": "shekharraja194@gmail.com", "competencyExpiry": "" },
  { "id": "22321", "name": "R Saravana", "designation": "Station Controller / Train Operator", "contact": "8264879518", "email": "saravanasara1105@gmail.com", "competencyExpiry": "" },
  { "id": "22322", "name": "Harish Pk", "designation": "Station Controller / Train Operator", "contact": "9611763603", "email": "harishmala35@gmail.com", "competencyExpiry": "" },
  { "id": "22323", "name": "Suresha B", "designation": "Station Controller / Train Operator", "contact": "8105576476", "email": "", "competencyExpiry": "" },
  { "id": "22454", "name": "VINAYAK", "designation": "Station Controller / Train Operator", "contact": "8139990330", "email": "vinayakgulbarga@gmail.com", "competencyExpiry": "" },
  { "id": "22455", "name": "VENKATESH N", "designation": "Station Controller / Train Operator", "contact": "8892629918", "email": "venkateshn0508@gmail.com", "competencyExpiry": "" },
  { "id": "22456", "name": "CHAITRANJALI U G", "designation": "Station Controller / Train Operator", "contact": "9663703038", "email": "chaitraugc@gmail.com", "competencyExpiry": "" },
  { "id": "22457", "name": "SHASHIKALA M", "designation": "Station Controller / Train Operator", "contact": "9035314655", "email": "hallikar.shashi@gmail.com", "competencyExpiry": "" },
  { "id": "22458", "name": "SHEELA S", "designation": "Station Controller / Train Operator", "contact": "9731867933", "email": "sheelatk93@gmail.com", "competencyExpiry": "" },
  { "id": "22460", "name": "SAHANA REDDY V", "designation": "Station Controller / Train Operator", "contact": "9686492319", "email": "sahanareddyv2001@gmail.com", "competencyExpiry": "" },
  { "id": "22461", "name": "ANANTHA", "designation": "Station Controller / Train Operator", "contact": "9880721042", "email": "", "competencyExpiry": "" },
  { "id": "22462", "name": "VINODKUMAR", "designation": "Station Controller / Train Operator", "contact": "8904476770", "email": "vidchavan1goal@gmail.com", "competencyExpiry": "" },
  { "id": "22463", "name": "MAMATHA D", "designation": "Station Controller / Train Operator", "contact": "9535562942", "email": "khushipruthviraj@gmail.com", "competencyExpiry": "" },
  { "id": "22464", "name": "NAVEEN KUMAR H S", "designation": "Station Controller / Train Operator", "contact": "7676109928", "email": "naveenhs0105@gmail.com", "competencyExpiry": "" },
  { "id": "22465", "name": "MADHU R", "designation": "Station Controller / Train Operator", "contact": "7019531706", "email": "", "competencyExpiry": "" },
  { "id": "22466", "name": "ARPITHA K R", "designation": "Station Controller / Train Operator", "contact": "9620719170", "email": "arpitha26kr@gmail.com", "competencyExpiry": "" },
  { "id": "22467", "name": "PRABHULINGA DODAMANI", "designation": "Station Controller / Train Operator", "contact": "9591324775", "email": "prabhumd123@gmail.com", "competencyExpiry": "" },
  { "id": "22468", "name": "NAYANA D R", "designation": "Station Controller / Train Operator", "contact": "6361531258", "email": "", "competencyExpiry": "" },
  { "id": "22469", "name": "BHAVYA K", "designation": "Station Controller / Train Operator", "contact": "8073452945", "email": "bhavyak864@gmail.com", "competencyExpiry": "" },
  { "id": "22470", "name": "PAVANKUMAR M", "designation": "Station Controller / Train Operator", "contact": "7022211486", "email": "", "competencyExpiry": "" },
  { "id": "22471", "name": "VASANTHAKUMARA D", "designation": "Station Controller / Train Operator", "contact": "9148398903", "email": "vasuisro5@gmail.com", "competencyExpiry": "" },
  { "id": "22472", "name": "A T PANKAJA", "designation": "Station Controller / Train Operator", "contact": "7899344288", "email": "pankajahema1234@gmail.com", "competencyExpiry": "" },
  { "id": "22473", "name": "VINAYAKA L", "designation": "Station Controller / Train Operator", "contact": "7483685947", "email": "vinayaka.062@gmail.com", "competencyExpiry": "" },
  { "id": "22474", "name": "SHASHIKALA Y M", "designation": "Station Controller / Train Operator", "contact": "8722052299", "email": "raju.nayakodi@gmail.com", "competencyExpiry": "" },
  { "id": "22475", "name": "PRATHIMA S", "designation": "Station Controller / Train Operator", "contact": "9900324924", "email": "prathimas1996@gmail.com", "competencyExpiry": "" },
  { "id": "22476", "name": "VIJAYALAXMI ANIGOL", "designation": "Station Controller / Train Operator", "contact": "8217780377", "email": "harish.jiya@gmail.com", "competencyExpiry": "" },
  { "id": "22477", "name": "MAMATHA V", "designation": "Station Controller / Train Operator", "contact": "7338099881", "email": "venkateshvenkat7478@gmail.com", "competencyExpiry": "" },
  { "id": "22478", "name": "MUDALAGIRIYAPPA K", "designation": "Station Controller / Train Operator", "contact": "7760606632", "email": "muruli776060@gmail.com", "competencyExpiry": "" },
  { "id": "22479", "name": "NAGALING", "designation": "Station Controller / Train Operator", "contact": "9972239719", "email": "", "competencyExpiry": "" },
  { "id": "22480", "name": "SOUMYA A", "designation": "Station Controller / Train Operator", "contact": "8197237811", "email": "smy.a04@gmail.com", "competencyExpiry": "" },
  { "id": "22481", "name": "MANOJ N", "designation": "Station Controller / Train Operator", "contact": "7022228900", "email": "majnpoojar126@gmail.com", "competencyExpiry": "" },
  { "id": "22482", "name": "RACHAYYA", "designation": "Station Controller / Train Operator", "contact": "8970173230", "email": "rachayya1997@gmail.com", "competencyExpiry": "" },
  { "id": "22483", "name": "MEGHA G", "designation": "Station Controller / Train Operator", "contact": "8861528135", "email": "meghaganesh0806@gmail.com", "competencyExpiry": "" },
  { "id": "22484", "name": "MANJUNATH SWAMY S M", "designation": "Station Controller / Train Operator", "contact": "9019394901", "email": "Manjunathsm44@gmail.com", "competencyExpiry": "" },
  { "id": "22485", "name": "BHAGYASHRI", "designation": "Station Controller / Train Operator", "contact": "8618596278", "email": "bhagyashree7675@gmail.com", "competencyExpiry": "" },
  { "id": "22486", "name": "CHETHANA S", "designation": "Station Controller / Train Operator", "contact": "9110452254", "email": "", "competencyExpiry": "" },
  { "id": "22487", "name": "PAVITHRA C", "designation": "Station Controller / Train Operator", "contact": "9663755016", "email": "pavithrachinnaswami123@gmail.com", "competencyExpiry": "" },
  { "id": "22488", "name": "ABHISHEK S P", "designation": "Station Controller / Train Operator", "contact": "9731332999", "email": "abhishekspsulleri@gmail.com", "competencyExpiry": "" },
  { "id": "22489", "name": "KIRAN NAIK R", "designation": "Station Controller / Train Operator", "contact": "7899343761", "email": "", "competencyExpiry": "" },
  { "id": "22490", "name": "ASHWINI BASHETTI", "designation": "Station Controller / Train Operator", "contact": "9901550067", "email": "ashwinibashetti@gmail.com", "competencyExpiry": "" },
  { "id": "22491", "name": "KALAVATHI K M", "designation": "Station Controller / Train Operator", "contact": "9113018612", "email": "akalagowda@gmail.com", "competencyExpiry": "" },
  { "id": "22492", "name": "NIRANJAN CM", "designation": "Station Controller / Train Operator", "contact": "9741423065", "email": "niranjankanja@gmail.com", "competencyExpiry": "" },
  { "id": "22493", "name": "KAVERI V S", "designation": "Station Controller / Train Operator", "contact": "9482977837", "email": "vskaveri2@gmail.com", "competencyExpiry": "" },
  { "id": "22494", "name": "MAHANTESH MAHADEV DIVANMAL", "designation": "Station Controller / Train Operator", "contact": "8123064054", "email": "mahantesh.rvce@gmail.com", "competencyExpiry": "" },
  { "id": "22495", "name": "ABDUL RAFI BAGALKOT", "designation": "Station Controller / Train Operator", "contact": "9972099742", "email": "abdulrafiab@gmail.com", "competencyExpiry": "" },
  { "id": "22496", "name": "RAJESH G", "designation": "Station Controller / Train Operator", "contact": "9113555618", "email": "", "competencyExpiry": "" },
  { "id": "22497", "name": "HARISH MURTHY HN", "designation": "Station Controller / Train Operator", "contact": "7259279774", "email": "HARISHMURTHY023@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22499", "name": "SHIVAKUMAR D", "designation": "Station Controller / Train Operator", "contact": "9035367414", "email": "shivakumard414@gmail.com", "competencyExpiry": "" },
  { "id": "22500", "name": "BHAVYASHREE K S", "designation": "Station Controller / Train Operator", "contact": "8123295621", "email": "pandrebhavya@gmail.com", "competencyExpiry": "" },
  { "id": "22501", "name": "GAJANAND", "designation": "Station Controller / Train Operator", "contact": "9742735641", "email": "", "competencyExpiry": "" },
  { "id": "22502", "name": "GANGAPPA", "designation": "Station Controller / Train Operator", "contact": "9686861465", "email": "arkeragangappa@gmail.com", "competencyExpiry": "" },
  { "id": "22503", "name": "JAMELABEGUM NADAF", "designation": "Station Controller / Train Operator", "contact": "9945269739", "email": "jamelabegumkhadi@gmail.com", "competencyExpiry": "" },
  { "id": "22504", "name": "MARULASIDDAIAH K N", "designation": "Station Controller / Train Operator", "contact": "9902927252", "email": "marulasiddaiahkn.1rn17ee406@gmail.com", "competencyExpiry": "" },
  { "id": "22505", "name": "VINAYA SALIYAN", "designation": "Station Controller / Train Operator", "contact": "8970573475", "email": "vinaysaliyan.93@gmail.com", "competencyExpiry": "" },
  { "id": "22506", "name": "SHWETHA S", "designation": "Station Controller / Train Operator", "contact": "9740376872", "email": "shwetha271997@gmail.com", "competencyExpiry": "" },
  { "id": "22507", "name": "SHEETHAL PANDU", "designation": "Station Controller / Train Operator", "contact": "7204615830", "email": "tcpandu@gmail.com", "competencyExpiry": "" },
  { "id": "22508", "name": "PRAKASH S BHASAGI", "designation": "Station Controller / Train Operator", "contact": "8073135724", "email": "bhasagips@gmail.com", "competencyExpiry": "" },
  { "id": "22509", "name": "MOHAN RAJ P", "designation": "Station Controller / Train Operator", "contact": "8892607771", "email": "monyak47@gmail.com", "competencyExpiry": "" },
  { "id": "22510", "name": "UMESH M N", "designation": "Station Controller / Train Operator", "contact": "8747863152", "email": "Umeshmn666@gmail.com", "competencyExpiry": "" },
  { "id": "22511", "name": "MAHABOOB BASHA K", "designation": "Station Controller / Train Operator", "contact": "9945615082", "email": "mabuk786@gmail.com", "competencyExpiry": "" },
  { "id": "22512", "name": "KUMAR", "designation": "Station Controller / Train Operator", "contact": "8152955306", "email": "kumarrathod397@gmail.com", "competencyExpiry": "" },
  { "id": "22513", "name": "SANDESH GOWD M", "designation": "Station Controller / Train Operator", "contact": "8951830913", "email": "msandesh130@gmail.com", "competencyExpiry": "" },
  { "id": "22514", "name": "SHAKUNTHALA R", "designation": "Station Controller / Train Operator", "contact": "7353357277", "email": "shakku.rjb@gmail.com", "competencyExpiry": "" },
  { "id": "22516", "name": "VARSHA", "designation": "Station Controller / Train Operator", "contact": "7259383940", "email": "VARSHACHORGASTI@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22517", "name": "RAMACHANDRA", "designation": "Station Controller / Train Operator", "contact": "9980527698", "email": "kramachandranayak@gmail.com", "competencyExpiry": "" },
  { "id": "22518", "name": "CHETHAN KUMAR N G", "designation": "Station Controller / Train Operator", "contact": "9916785114", "email": "chethanideas@gmail.com", "competencyExpiry": "" },
  { "id": "22519", "name": "CHETHANKUMAR M", "designation": "Station Controller / Train Operator", "contact": "9740746777", "email": "chethan02kumar@gmail.com", "competencyExpiry": "" },
  { "id": "22520", "name": "RASHMI L", "designation": "Station Controller / Train Operator", "contact": "9900498498", "email": "rashmi.lakshmana29@gmail.com", "competencyExpiry": "" },
  { "id": "22521", "name": "SANTOSH JANIWAR", "designation": "Station Controller / Train Operator", "contact": "9972578405", "email": "", "competencyExpiry": "" },
  { "id": "22522", "name": "HARSHITH D", "designation": "Station Controller / Train Operator", "contact": "8792735263", "email": "harshithd1997@gmail.com", "competencyExpiry": "" },
  { "id": "22524", "name": "RAVIKIRAN K", "designation": "Station Controller / Train Operator", "contact": "7892913017", "email": "ravikiran165@gmail.com", "competencyExpiry": "" },
  { "id": "22525", "name": "SHIVASHANKAR M", "designation": "Station Controller / Train Operator", "contact": "9743475745", "email": "", "competencyExpiry": "" },
  { "id": "22526", "name": "SRINIVAS MURTHY HR", "designation": "Station Controller / Train Operator", "contact": "9972844362", "email": "", "competencyExpiry": "" },
  { "id": "22527", "name": "NAVEENA G N", "designation": "Station Controller / Train Operator", "contact": "8748003161", "email": "", "competencyExpiry": "" },
  { "id": "22528", "name": "ARUN KUMAR TR", "designation": "Station Controller / Train Operator", "contact": "7348814475", "email": "", "competencyExpiry": "" },
  { "id": "22529", "name": "MAHESH KUMAR M", "designation": "Station Controller / Train Operator", "contact": "8197567143", "email": "", "competencyExpiry": "" },
  { "id": "22531", "name": "RAMAMOORTHY M", "designation": "Station Controller / Train Operator", "contact": "9486524504", "email": "", "competencyExpiry": "" },
  { "id": "22536", "name": "AJIT KULAGERI", "designation": "Station Controller / Train Operator", "contact": "7406022037", "email": "ajitkulageri@gmail.com", "competencyExpiry": "" },
  { "id": "22537", "name": "CHETAN CHITRAGAR", "designation": "Station Controller / Train Operator", "contact": "7019346112", "email": "Chitrgarchetan@gmail.com", "competencyExpiry": "" },
  { "id": "22538", "name": "MANOJ K", "designation": "Station Controller / Train Operator", "contact": "8497077489", "email": "majk1997ckm@gmail.com", "competencyExpiry": "" },
  { "id": "22539", "name": "PRASANNA A S", "designation": "Station Controller / Train Operator", "contact": "9916563998", "email": "asprasanna48@gmail.com", "competencyExpiry": "" },
  { "id": "22540", "name": "ANITHA B", "designation": "Station Controller / Train Operator", "contact": "9901362900", "email": "anithar1920@gmail.com", "competencyExpiry": "" },
  { "id": "22541", "name": "AJITH J", "designation": "Station Controller / Train Operator", "contact": "9886537712", "email": "ajshetty99@gmail.com", "competencyExpiry": "" },
  { "id": "22542", "name": "CHAITHRA C S", "designation": "Station Controller / Train Operator", "contact": "7892955774", "email": "chaithra.jaanumanu06@gmail.com", "competencyExpiry": "" },
  { "id": "22544", "name": "VIGHNESH", "designation": "Station Controller / Train Operator", "contact": "8971898812", "email": "vighneshamin@gmail.com", "competencyExpiry": "" },
  { "id": "22545", "name": "PRADEEPA ACHARI", "designation": "Station Controller / Train Operator", "contact": "9019732855", "email": "pradeepachar4@gmail.com", "competencyExpiry": "" },
  { "id": "22546", "name": "VIJAYA B S", "designation": "Station Controller / Train Operator", "contact": "9743281569", "email": "vijaysomashekar33@gmail.com", "competencyExpiry": "" },
  { "id": "22547", "name": "AKSHAYAKUMAR N", "designation": "Station Controller / Train Operator", "contact": "9071868024", "email": "akshaykumarakki3333@gmail.com", "competencyExpiry": "" },
  { "id": "22548", "name": "NAGESH", "designation": "Station Controller / Train Operator", "contact": "7892524084", "email": "nageshnadagatti109@gmail.com", "competencyExpiry": "" },
  { "id": "22549", "name": "GOPAL K KULMIYALLAPUR", "designation": "Station Controller / Train Operator", "contact": "8971641637", "email": "gopikrishnakk2@gmail.com", "competencyExpiry": "" },
  { "id": "22551", "name": "SUDARSHAN", "designation": "Station Controller / Train Operator", "contact": "8660935800", "email": "sudarshan8071@gmail.com", "competencyExpiry": "" },
  { "id": "22553", "name": "ASHWINI S", "designation": "Station Controller / Train Operator", "contact": "9743756523", "email": "", "competencyExpiry": "" },
  { "id": "22559", "name": "RAVEESHA S", "designation": "Station Controller / Train Operator", "contact": "8050799612", "email": "raveeshgowda.s@gmail.com", "competencyExpiry": "" },
  { "id": "22560", "name": "ANITHA DILEEP JANAGOND", "designation": "Station Controller / Train Operator", "contact": "7204060184", "email": "anithadj7@gmail.com", "competencyExpiry": "" },
  { "id": "22561", "name": "Sajeet Kumar Rai", "designation": "Station Controller / Train Operator", "contact": "8826191184", "email": "sajeetrai@gmail.com", "competencyExpiry": "" },
  { "id": "22562", "name": "Ashim Majumder", "designation": "Station Controller / Train Operator", "contact": "9402137124", "email": "ashimmajumder@gmail.com", "competencyExpiry": "" },
  { "id": "22563", "name": "J HARI KRISHNA", "designation": "Station Controller / Train Operator", "contact": "9052512886", "email": "", "competencyExpiry": "" },
  { "id": "22564", "name": "MANJUNATH BAGEWADI", "designation": "Station Controller / Train Operator", "contact": "9891366911", "email": "nath7593.mb@gmail.com", "competencyExpiry": "" },
  { "id": "22565", "name": "JILJO PAUL GEORGE", "designation": "Station Controller / Train Operator", "contact": "8015837037", "email": "JILJILOS1985@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22566", "name": "AMIT KUMAR JHA", "designation": "Station Controller / Train Operator", "contact": "8861099283", "email": "LOVINGAMITJHA@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22567", "name": "Ravi Anand Torvesh", "designation": "Station Controller / Train Operator", "contact": "8155027442", "email": "ravianandtorvesh@gmail.com", "competencyExpiry": "" },
  { "id": "22568", "name": "Elamparithi J", "designation": "Station Controller / Train Operator", "contact": "9087409447", "email": "elamsvl@gmail.com", "competencyExpiry": "" },
  { "id": "22569", "name": "SHASHI KUMARA", "designation": "Station Controller / Train Operator", "contact": "8073421841", "email": "shashigowda1987@gmail.com", "competencyExpiry": "" },
  { "id": "22570", "name": "SUNIL KUMAR N", "designation": "Station Controller / Train Operator", "contact": "9160544939", "email": "sportysunil18@gmail.com", "competencyExpiry": "" },
  { "id": "22571", "name": "MATHETI GOVARDHAN", "designation": "Station Controller / Train Operator", "contact": "8295565180", "email": "GOVARDHANREDDY24@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22572", "name": "SUNIL KUMAR SHARMA", "designation": "Station Controller / Train Operator", "contact": "8800900501", "email": "SUNILSHARMA3341@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22573", "name": "V S ANANDA MURALI VEGI", "designation": "Station Controller / Train Operator", "contact": "9560347745", "email": "murali1569@gmail.com", "competencyExpiry": "" },
  { "id": "22577", "name": "REJIN K", "designation": "Station Controller / Train Operator", "contact": "9879710869", "email": "rejinafs@gmail.com", "competencyExpiry": "" },
  { "id": "22578", "name": "gopisetti subrahmanyam", "designation": "Station Controller / Train Operator", "contact": "9490450894", "email": "", "competencyExpiry": "" },
  { "id": "22580", "name": "Suryakant Chaturvedi", "designation": "Station Controller / Train Operator", "contact": "9149925304", "email": "SURYA84AF@GMAIL.COM", "competencyExpiry": "" },
  { "id": "22581", "name": "Rajeev Kumar Singh", "designation": "Station Controller / Train Operator", "contact": "8738085184", "email": "", "competencyExpiry": "" },
  { "id": "22585", "name": "SIVA KUMAR ANUPOJU", "designation": "Station Controller / Train Operator", "contact": "9813285610", "email": "princesiva1006@gmail.com", "competencyExpiry": "" },
  { "id": "22586", "name": "Subhasish Chakraborty", "designation": "Station Controller / Train Operator", "contact": "9500992428", "email": "", "competencyExpiry": "" },
  { "id": "20726", "name": "Nagesha N", "designation": "Station Superintendent", "contact": "9110238017", "email": "nageshn444@gmail.com", "competencyExpiry": "" }
];
